// Telas 05-11 (executar + auditar) e mockups da pesquisa Baby & Parenting > Montessori (AU).
import * as S from './shell.mjs';
import { LOJAS, ECON, build, CONV_PCT, CPA_PCT_V, MIN, FILTRADOS } from './dados-pesquisa.mjs';
const { esc, n, usd, aud, pct, nat, na, pill, stat, note, table, td, tr, evidence, btn, doc, pageHead, toc, sec, footer, legendNat, legendVer, dfn, imgcard, swatches, VER_CLS } = S;

const ALI = q => 'https://www.aliexpress.com/w/wholesale-' + encodeURIComponent(q.replace(/\s+/g, '-')) + '.html?SortType=total_tranpro_desc';
const PAPEL = { 'switch-busy-board': 'produto principal (core)', 'quiet-time-activity-cards': 'order bump (digital)', 'travel-busy-book': 'upsell (carrinho)', 'quiet-time-kit': 'bundle', 'felt-christmas-tree': 'sazonal (Natal)', 'busy-board-carry-bag': 'add-on' };
const SOURCING = {
  'switch-busy-board': ['montessori busy board wooden led light switch toddler', 'US$ 8-14 + frete US$ 6-10'],
  'quiet-time-activity-cards': ['(produto digital: você cria o PDF no Canva, sem fornecedor)', 'A$ 0'],
  'travel-busy-book': ['montessori felt busy book toddler travel quiet book', 'US$ 5-9 + frete US$ 4-6'],
  'quiet-time-kit': ['board + busy book + bolsa (mesmo agente, um pacote)', 'A$ 46-56'],
  'felt-christmas-tree': ['felt christmas tree toddler velcro ornaments wall', 'US$ 6-10 + frete US$ 5-8'],
  'busy-board-carry-bag': ['quilted cotton baby travel bag padded zip', 'US$ 2-4 + frete'],
};
const PALETA = [['Creme', '#FBF8F1'], ['Areia', '#F3ECDD'], ['Eucalipto', '#3F5E4E'], ['Amarelo wattle', '#E3A82B'], ['Argila', '#C9704E'], ['Tinta', '#2A2A26'], ['Borda', '#E4DCCB']];
const MAIN4 = LOJAS.slice(0, 4);

/* ================= 05 ESTRATEGIA ================= */
export function estrategia() {
  const cards = LOJAS.map(l => '<a class="card link" href="loja-' + l.slug + '.html"><span class="eyebrow ' + VER_CLS[l.veredito] + '">' + esc(l.lado) + '</span><h3>' + esc(l.nome) + ' ' + pill(l.veredito, VER_CLS[l.veredito]) + '</h3><p>' + esc(l.oQueCopiar) + '</p><p>' + pill('nível ' + l.nivel, 'b') + ' ' + pill(l.modelo, 'n') + ' ' + pill(l.defens, l.defens === 'CONSTRUÍVEL' ? 'g' : 'a') + '</p></a>').join('');
  const bench = table(['Loja', { t: 'Ativos', num: true }, { t: 'Sobrevivência', num: true }, { t: 'Receita/mês est.', num: true }, { t: 'Ticket', num: true }, { t: 'Mídia/mês est.', num: true }, 'Veredito'], LOJAS.map(l => tr([td(esc(l.nome)), td(n(l.ativos, 0), 'num'), td(l.sobrev != null ? pct(l.sobrev) : na('histórico = ativos'), 'num'), td(l.fat ? usd(l.fat) + ' <small>(incerto)</small>' : na('SimilarWeb bloqueado'), 'num'), td(usd(l.ticket, 2), 'num'), td(l.midiaMes ? usd(l.midiaMes) : '-', 'num'), td(pill(l.veredito, VER_CLS[l.veredito]))])));
  const body = pageHead({ eyebrow: '05 · execução · estratégia · onde entrar', h1: 'Onde está a <em>porta de entrada</em>', answer: 'No busy board de interruptores, vendido na Austrália pelo sossego sem tela, com a segurança provada em imagem e o kit de presente no Natal. É o que as 4 lojas modelo vendem e o que um iniciante monta com 6 itens.', meta: ['ciclo de vida: ESCALANDO', 'nível iniciante', '5 lojas comparadas'] }) +
    toc([['resumo', 'Resumo em 1 minuto'], ['benchmark', 'Benchmark'], ['ranking', 'Ranking'], ['angulo', 'Ângulo dominante'], ['defensabilidade', 'Defensabilidade'], ['voz', 'Voz do mercado'], ['quando', 'Quando entrar'], ['regras', 'Regras de iniciante'], ['suas', 'Decisões suas']]) +
    sec('resumo', '00', 'Resumo em 1 minuto', '<div class="card"><p><b>Vale a pena?</b> Sim. Quatro lojas que só revendem de fornecedor estão vendendo busy board agora (três delas como produto principal, de US$ 40 a 50), com anúncio que fica mais de 100 dias no ar, e uma delas é australiana e está crescendo.</p><p><b>Faz sentido para iniciante?</b> Sim, com três cuidados: um produto só (o board de interruptores), um país (Austrália) e fornecedor com laudo de segurança. Carregador de bebê também vende muito, mas é produto regulado com risco de queda: ficou fora.</p><p><b>O que muda o jogo?</b> Mostrar o que nenhum concorrente mostra: a peça que não sai quando puxada e a pilha presa com parafuso. Depois do recall de 276 mil busy boards na Amazon, segurança provada vira motivo de compra.</p></div>') +
    sec('benchmark', '01', 'Tabela de benchmark (todas as lojas)', bench + note('Só a Montessori Paradise tem receita estimada (proxy de 117 reviews verificados, "estimado incerto"). O SimilarWeb bloqueou a coleta das outras e você preferiu seguir sem a extensão. O tamanho das outras é lido pelos anúncios ativos e pela longevidade do campeão.', 'a', 'limite')) +
    sec('ranking', '02', 'Ranking de oportunidades', legendVer() + '<div class="grid g2">' + cards + '</div>' + note('<b>Oportunidade nº 1:</b> loja de busy board de interruptores na Austrália (molde Lovealotter na simplicidade + toddla.co no ângulo e no bundle). Preço A$ 69,95 + A$ 9,95 de frete, ' + dfn('CPA') + ' de equilíbrio ' + aud(ECON.cpaEquilibrioCore) + ' só com o board; com PDF e busy book, sobra ' + aud(ECON.margemEscCons) + ' por pedido a CPA de A$ 35.', 'g')) +
    sec('angulo', '03', 'Ângulo dominante do nicho', '<div class="card"><span class="eyebrow g">big idea</span><h3>"The switches they\'re actually allowed to touch."</h3><p>A criança já mexe em todo interruptor, trinco e zíper da casa. O board junta tudo num lugar seguro, e o adulto ganha 20 minutos sem tela e sem culpa.</p></div>' +
      note('<b>Mecanismo:</b> atividades da vida real (interruptor, trinco, zíper, botão giratório) presas com parafuso num painel de madeira, com LED alimentado por pilha AA em tampa parafusada. Prometer "concentração e sossego", nunca "desenvolvimento do cérebro" ou "ajuda no TDAH": é promessa médica.', 'b') +
      note('<b>Ângulo de anúncio:</b> o proibido liberado (Lovealotter, 120 dias no ar) + o sossego do adulto (toddla.co, UGC de mãe) + a prova de segurança (ninguém mostra). "Motricidade fina" aparece em 21 marcas: é argumento de apoio, não gancho.', 'g')) +
    sec('defensabilidade', '04', 'Dá para construir algo sólido aqui?', table(['Loja', 'Sinal', 'Selo'], [
      tr([td('toddla.co'), td('5 anos de loja, 70 mil seguidores, marca "Toddla™" em todo o catálogo, Google Ads e 3 páginas no Meta'), td(pill('CONSTRUÍVEL', 'g'))]),
      tr([td('Tibatoes'), td('catálogo de 250 itens virando generalista (óculos de natação), Tranco caindo'), td(pill('ARBITRAGEM', 'a'))]),
      tr([td('Lovealotter'), td('produtos de vários fornecedores, 1.574 seguidores, só Meta'), td(pill('ARBITRAGEM', 'a'))]),
      tr([td('Montessori Paradise'), td('loja de 9 meses, nenhum perfil social, prova social inflada'), td(pill('ARBITRAGEM', 'a'))]),
    ]) + note('A toddla.co mostra que dá para construir marca neste nicho: mesmo sendo dropship, ela tem nome próprio, comunidade no Instagram e recompra por bundle. Pago x orgânico ' + na('SimilarWeb bloqueado') + ', então a leitura vem de catálogo, redes e longevidade.', 'b')) +
    sec('voz', '05', 'Voz do mercado', table(['Objeção', 'Gatilho', 'Linguagem observada', 'Brecha'], [
      tr([td('Vai soltar uma peça'), td('recall de busy board na Amazon'), td('"a child managed to completely pull the bottom piece with the round beads off"'), td('vídeo e foto do teste de puxar + página "Our Safety Promise"')]),
      tr([td('Vai enjoar em 2 minutos'), td('criança que larga tudo'), td('"Toddlers can be finicky, you never know what will keep them playing"'), td('PDF com 30 jeitos de usar o board + vídeo de 20 minutos')]),
      tr([td('Barulho e pilha'), td('buzina e pilha que acaba'), td('"the horn button can be an annoyance / battery stopped working after about 5 uses"'), td('sem buzina; luz pequena opcional; pilha AA comum')]),
      tr([td('Qualidade'), td('produto que chega frágil ou pequeno'), td('"felt cheaply made / smaller than expected"'), td('foto com escala (na mão do adulto) e madeira lisa em close')]),
    ]) + '<div class="btns" style="margin-top:10px">' + S.btn('Fonte: recall Esjay (276 mil)', 'https://www.wftv.com/news/trending/recall-alert-276k-montessori-toddler-toys-recalled-over-choking-hazard/XOJ4576EE5EUXKH5X6MFDWIOSI/', 'sm', true) + S.btn('Fonte: PBS sobre tela', 'https://www.pbs.org/newshour/education/screen-time-toddlers-parents-dont-feel-guilty', 'sm', true) + '</div>') +
    sec('quando', '06', 'Quando entrar', note('<b>Ciclo de vida: ESCALANDO.</b> Lojas de 2025 e 2026 com centenas de anúncios ativos (Tibatoes, Montessori Paradise) e a australiana toddla.co subindo no Tranco. Demanda (autocomplete em 1º lugar) e mídia (anúncios de 99 a 120 dias) apontam juntas. Divergência: a Tibatoes já está trocando o busy board por outros produtos, sinal de que o anúncio de busy board está cansando no público americano. Na Austrália, a disputa é menor.', 'g') +
      evidence({ fonte: 'Meta Ads por page_id; datas de catálogo; Tranco; matriz de países.', obs: 'Campanhas de Natal começando agora (Montessori Paradise há 15 dias, toddla.co com árvore de feltro).', interp: 'A janela está aberta, com o maior pico do ano em novembro e dezembro, que na Austrália também é férias de verão (viagem de carro).', dec: 'Entrar agora, para ter anúncio validado antes de 15 de novembro.', next: 'Amostra esta semana; loja no ar em 16 dias.' })) +
    sec('regras', '07', 'Regras de iniciante', '<ul class="cl g"><li>Um produto-herói, uma loja, um país. ' + nat('rec') + '</li><li>Nada de catálogo de 250 itens: 6 bastam. ' + nat('rec') + '</li><li>Nunca anunciar sem laudo de segurança do fornecedor e sem o teste de puxar a amostra. ' + nat('rec') + '</li><li>Nunca vender board com bateria de botão (moeda): só pilha AA com tampa parafusada. ' + nat('rec') + '</li><li>Não copiar alegações de concorrente ("80K+ happy customers", "11.000 reviews", "We got copied"). ' + nat('rec') + '</li><li>Não prometer ajuda em TDAH, autismo ou desenvolvimento cerebral. ' + nat('rec') + '</li><li>Parar o anúncio pelo critério de parada do plano, não por sensação. ' + nat('rec') + '</li></ul>') +
    sec('suas', '08', 'As decisões que são suas', '<div class="grid g2">' +
      '<div class="card"><span class="eyebrow a">decisão 1</span><h3>Austrália ou EUA?</h3><p>Dado: EUA têm ' + '686' + ' anúncios ativos de "montessori toys" contra 407 na Austrália, mas cobram tarifa de 17,5% a 35% e certificado CPC. Trade-off: os EUA têm mais gente comprando, a Austrália é mais simples e barata de operar. Recomendação: Austrália no início; EUA só com fornecedor que entregue o CPC.</p></div>' +
      '<div class="card"><span class="eyebrow a">decisão 2</span><h3>Board com luz ou sem pilha?</h3><p>Dado: a Lovealotter vende o de LED há 120 dias; a toddla.co vende "No batteries. No flashing lights." Trade-off: a luz chama atenção no vídeo; sem pilha é mais seguro e calmo. Recomendação: LED com pilha AA e tampa parafusada; teste um anúncio "sem pilha" no mês 2.</p></div>' +
      '<div class="card"><span class="eyebrow a">decisão 3</span><h3>Preço "de" no board?</h3><p>Dado: todos mostram preço riscado (US$ 79,98, US$ 80,98). Trade-off: a âncora ajuda, mas na Austrália a ACCC multa "preço de" que nunca foi praticado. Recomendação: use o "de" só se praticou esse preço por um tempo real; senão, mostre a economia do kit (que é verdadeira: A$ 124,85 separados contra A$ 99,95).</p></div>' +
      '<div class="card"><span class="eyebrow a">decisão 4</span><h3>Garantia de 30 ou 45 dias?</h3><p>Dado: Tibatoes 30 dias; Montessori Paradise 45. Trade-off: mais dias vende mais e devolve mais. Recomendação: 30 dias "happy-play" no início; subir para 45 quando a taxa de devolução estiver medida.</p></div></div>') +
    footer(false);
  return doc({ title: 'Estratégia · Montessori', current: 'estrategia', screen: { code: '05', title: 'Estratégia' }, body, next: { t: 'Abrir o plano de ação do zero à venda', b: 'Plano de ação', h: 'plano-de-acao.html' } });
}

/* ================= 06 PLANO ================= */
export function plano() {
  const prods = build.produtos;
  const cat = table(['Produto', 'Papel', 'Palavra-chave de sourcing', 'Fornecedor (busca ordenada por vendas)', 'Custo est.', { t: 'Preço', num: true }, { t: 'De', num: true }], prods.map(p => tr([td('<b>' + esc(p.titulo) + '</b>'), td(PAPEL[p.handle]), td(esc(SOURCING[p.handle][0])), td(p.handle === 'quiet-time-activity-cards' ? 'Canva (você cria)' : '<a href="' + ALI(SOURCING[p.handle][0]) + '" target="_blank" rel="noopener">AliExpress ↗</a>'), td(SOURCING[p.handle][1] + ' ' + nat('inf')), td(aud(+p.preco), 'num'), td(p.de ? aud(+p.de) : '-', 'num')])));
  const esc1 = table(['Degrau', 'Item', { t: 'Preço', num: true }, 'Custo est.', { t: 'Aceite', num: true }, 'Por quê'], [
    tr([td('Produto principal'), td('Switch and Latch Busy Board'), td('A$ 69,95 <s>A$ 119,95</s>', 'num'), td('A$ 28 (produto + frete)'), td('-', 'num'), td('campeão de 3 das 4 lojas modelo (US$ 39,99 a US$ 50,60)')]),
    tr([td(dfn('order bump')), td('Quiet Time Activity Cards, PDF (na página do produto)'), td('A$ 9,95', 'num'), td('A$ 0 (digital)'), td('30%', 'num'), td('a Tibatoes vende um PDF imprimível a US$ 9,95; responde à objeção "vai enjoar"')]),
    tr([td(dfn('upsell')), td('Travel Busy Book (no carrinho)'), td('A$ 39,95', 'num'), td('A$ 18'), td('12%', 'num'), td('busy book é o 2º produto mais vendido do nicho (toddla.co a US$ 49,99); leva o pedido acima de A$ 99 (frete grátis)')]),
    tr([td('Bundle'), td('Quiet Time Kit (board + busy book + bolsa)'), td('A$ 99,95 <s>A$ 124,85</s>', 'num'), td('A$ 51'), td('-', 'num'), td('bundles de US$ 99,99 nas lojas modelo; presente de avó no Natal')]),
  ]);
  const pl = table(['Cenário', { t: 'Receita', num: true }, { t: 'Custos (produto, frete, taxa)', num: true }, { t: 'CPA', num: true }, { t: 'Margem por pedido', num: true }], [
    tr([td('Só o board · CPA conservador A$ 35'), td(aud(ECON.receitaCore), 'num'), td(aud(ECON.custo + ECON.frete + ECON.taxa), 'num'), td('A$ 35,00', 'num'), td(aud(ECON.margemCoreCons) + ' (' + pct(ECON.margemCoreCons / ECON.receitaCore * 100) + ')', 'num')]),
    tr([td('Escada completa · CPA A$ 35'), td(aud(ECON.aov), 'num'), td(aud(ECON.custoEsc), 'num'), td('A$ 35,00', 'num'), td(aud(ECON.margemEscCons) + ' (' + pct(ECON.margemEscCons / ECON.aov * 100) + ')', 'num')]),
    tr([td('Kit de presente · CPA A$ 35'), td(aud(ECON.kit), 'num'), td(aud(ECON.kitCusto + ECON.kit * ECON.taxaPct), 'num'), td('A$ 35,00', 'num'), td(aud(ECON.margemKitCons) + ' (' + pct(ECON.margemKitCons / ECON.kit * 100) + ')', 'num')]),
    tr([td('Escada completa · CPA do benchmark IRP (' + n(CPA_PCT_V, 2) + '% da receita)'), td(aud(ECON.aov), 'num'), td(aud(ECON.custoEsc), 'num'), td(aud(ECON.aov * CPA_PCT_V / 100), 'num'), td(aud(ECON.margemEscIrp), 'num')]),
  ]);
  const body = pageHead({ eyebrow: '06 · execução · plano de ação · do zero à venda em 16 dias', h1: 'Wattlebee', answer: 'Busy board de interruptores para pais e avós de crianças de 1 a 3 anos, vendido na Austrália a A$ 69,95, com cartões de atividade em PDF, busy book de viagem e kit de presente.', meta: ['nível iniciante', 'Austrália · inglês · AUD', '6 itens (5 físicos + 1 digital)'] }) +
    toc([['mercado', 'Mercado'], ['marca', 'Marca'], ['avatar', 'Avatar'], ['catalogo', 'Catálogo'], ['oferta', 'Oferta'], ['investimento', 'Investimento'], ['funil', 'Funil'], ['referencias', 'Referências'], ['regua', 'Régua'], ['suas', 'Decisões suas'], ['checklist', 'Checklist']]) +
    sec('mercado', '00', 'Decisão de mercado', '<div class="card"><p><b>País da loja:</b> Austrália. <b>Idioma:</b> inglês (grafia australiana: "colour", "nappy", "pram"). <b>Moeda:</b> AUD, preço com ' + dfn('GST') + ' incluído. Fase 2: Nova Zelândia com a mesma loja. Por quê: ver ' + btn('Mercados', 'mercados.html', 'sm') + '</p></div>') +
    sec('marca', '01', 'A marca', '<dl class="kv"><dt>Quem é</dt><dd>Wattlebee, marca australiana de brinquedos calmos e sem tela para crianças de 1 a 3 anos.</dd><dt>O que vende</dt><dd>Busy board de interruptores, busy book de viagem, árvore de feltro de Natal, cartões de atividade em PDF e o kit de presente.</dd><dt>Pra quem</dt><dd>Mãe ou pai de criança de 12 a 36 meses que trabalha, cozinha ou tem outro filho e precisa de 20 minutos sem tela; e a avó que quer acertar o presente de Natal.</dd><dt>Onde</dt><dd>Loja própria Shopify, anúncios no Facebook e Instagram, Austrália.</dd><dt>Como se diferencia</dt><dd>Prova a segurança em imagem (peça que não sai, pilha parafusada) e ensina 30 jeitos de usar o board, em vez de só dizer "educativo".</dd><dt>Por quê</dt><dd>"E se soltar uma peça?" e "vai enjoar em 2 minutos" são as objeções número 1 e 2, e nenhum concorrente responde em imagem.</dd></dl>' +
      note('Ângulo de anúncio: <b>"The switches they\'re actually allowed to touch."</b> Nome checado: "Wattlebee" não aparece nos catálogos e anúncios coletados (busca em todos os JSON da pesquisa) nem na web. Wattle é a acácia-símbolo da Austrália; "bee" lembra "busy bee".', 'g')) +
    sec('avatar', '02', 'Avatar', table(['Momento', 'Dores', 'Desejo', 'Objeções', 'Linguagem'], [tr([td('Fim de tarde (a "hora do caos"), café da manhã, viagem de carro'), td('culpa de dar o tablet, criança mexendo em todo interruptor da casa, jantar que não sai'), td('20 minutos de sossego sem culpa'), td('"vai soltar peça?", "vai enjoar?", "é barulhento?"'), td('"little hands", "screen free", "coffee still hot", "5pm crisis"')]), tr([td('Outubro a dezembro'), td('medo de errar o presente do neto'), td('um presente que a criança usa de verdade'), td('"será que é a idade certa?"'), td('"Grandma\'s favorite gift", "won\'t regret buying"')])])) +
    sec('catalogo', '03', 'Arquitetura de catálogo', cat + note('Arquitetura: 6 itens em 3 coleções (Busy Boards, Quiet Time On The Go, Christmas Gifts). Coleção principal: Busy Boards. Por que 6 e não mais: o board resolve a dor central; o PDF e o busy book respondem às objeções "vai enjoar" e "e na viagem?"; a árvore e o kit pegam o pico de Natal; a bolsa só existe porque cabe no frete do kit. Um 7º item (por exemplo, um brinquedo para bebê de 6 meses) seria outro comprador e outro anúncio. Custos são <b>estimativa</b>: os links abrem a busca do AliExpress ordenada por vendas; o fornecedor exato sai da amostra e do laudo. Copy, SEO e menu completos em ' + btn('Catálogo e oferta', 'catalogo-oferta.html', 'sm'), 'b')) +
    sec('oferta', '04', 'Escada de oferta e P&amp;L', esc1 + '<div class="grid g4" style="margin-top:12px">' + stat({ v: aud(ECON.aov), l: 'AOV projetado (ticket médio)', d: '69,95 + 9,95 x 30% + 39,95 x 12% + frete', k: 'calc' }) + stat({ v: aud(ECON.cpaEquilibrioCore), l: 'CPA de equilíbrio (só board)', k: 'calc' }) + stat({ v: n(ECON.aov / ECON.custoEsc, 2) + 'x', l: 'ROAS de equilíbrio (por margem)', d: 'receita ÷ custos sem anúncio', k: 'calc' }) + stat({ v: 'A$ 28', l: 'custo do board posto na AU', d: 'estimativa, sem amostra (câmbio US$ 1 = A$ 1,52)', k: 'inf' }) + '</div>' + pl +
      note('Em resumo: o board sozinho já paga um anúncio frio de A$ 35 e sobra ~A$ 14. O PDF (custo zero) e o busy book aumentam a sobra para ~A$ 19. O cenário do benchmark IRP é otimista porque mistura todos os canais (inclusive cliente que volta); planeje pelo cenário de A$ 35. ' + dfn('GST') + ': abaixo de A$ 75 mil por ano em vendas para a Austrália não há registro nem recolhimento.', 'a', 'em resumo')) +
    sec('investimento', '05', 'Investimento mínimo do teste', '<div class="grid g4">' + stat({ v: aud(ECON.testeDia * ECON.testeDias, 0), l: 'anúncios: 3 x A$ 20/dia por 7 dias', k: 'rec' }) + stat({ v: aud(ECON.amostra, 0), l: 'amostras de 2 fornecedores com frete', d: 'estimativa', k: 'inf' }) + stat({ v: aud(ECON.shopify, 0), l: 'Shopify + domínio no 1º mês', d: 'estimativa', k: 'inf' }) + stat({ v: aud(ECON.investimentoTeste, 0), l: 'total para saber se vende', k: 'calc' }) + '</div>' + note('Esse valor não é uma pergunta: ele sai da conta. Com CPA de equilíbrio de A$ 49,50, sete dias a A$ 60 por dia dão de 8 a 12 vendas, o mínimo para o Facebook sair da fase de aprendizado e você ler o resultado.', 'b')) +
    sec('funil', '06', 'Funil, orçamento e cronograma', '<ol class="steps"><li><b>Dias 1 a 4:</b> amostra de 2 fornecedores (busy board de interruptores, pilha AA com tampa parafusada) com laudo de segurança de brinquedo.</li><li><b>Dias 5 a 9:</b> teste de puxar cada peça; criança de 1 a 3 anos brincando 20 minutos com supervisão; escolher o fornecedor.</li><li><b>Dias 7 a 12:</b> loja no ar (6 itens), seguindo o blueprint; página "Our Safety Promise".</li><li><b>Dias 12 a 16:</b> filmar a amostra + imagens; 3 anúncios a A$ 20/dia (A$ 60/dia), mulheres e homens de 25 a 65 anos na Austrália, interesses de pais e avós.</li><li><b>De 1º de novembro em diante:</b> ligar o anúncio da avó e o kit de presente; canal secundário: Google Search com A$ 10/dia em "montessori busy board australia" só depois do Meta validar (30 vendas).</li></ol>' +
      table(['Etapa do funil', 'O que acontece', 'Onde está'], [tr([td('Anúncio'), td('criança no interruptor da casa → board → café quente ao fundo'), td('Criativos (tela 04)')]), tr([td('Pré-venda (opcional, Natal)'), td('lista "5 gifts toddlers actually play with" → botão para o kit'), td('modelo: Montessori Paradise /pages/christmas-gifts-grandmas-are-buying')]), tr([td('Página de produto'), td('galeria com prova de segurança, preço, PDF como bump, objeções'), td('Blueprint (tela 08)')]), tr([td('Carrinho'), td('busy book de viagem como upsell (passa de A$ 99, frete grátis)'), td('build.json · upsell_carrinho')])]) +
      note('<b>Critério de parada:</b> com A$ 100 gastos num anúncio, se o CTR estiver abaixo de 0,8%, pausar. Com A$ 150 gastos, se o CPA estiver acima de A$ 52 (1,5x o CPA de A$ 35), trocar o criativo; acima de A$ 87 (2,5x), pausar e rever o ângulo. Se a página de produto tiver mais de 100 visitas e menos de 8% de adição ao carrinho, revisar preço e fotos antes de subir verba.', 'r', 'critério de parada')) +
    sec('referencias', '07', 'Referências para modelar', '<div class="grid g2"><div class="card"><span class="eyebrow b">anúncio</span><p>Lovealotter "Finally, A Toy They\'re Allowed To Touch" (~107 dias no ar) e toddla.co "Five minutes, coffee still hot" (UGC de mãe).</p>' + btn('Biblioteca Lovealotter', S.adlib('lovealotter.com'), 'sm', true) + btn('Biblioteca toddla.co', S.adlib('toddla.co'), 'sm', true) + '</div><div class="card"><span class="eyebrow b">página de produto</span><p>toddla.co "Montessori Busy Board": 16 fotos com criança real, closes das peças, foto na mala de viagem.</p>' + btn('Abrir PDP toddla.co', 'https://toddla.co/products/toddla-montessori-busy-board', 'sm', true) + '</div></div>' +
      table(['Referência', 'Copiar', 'Evitar'], [tr([td('toddla.co'), td('ângulo calmo, UGC de mãe, bundle de presente'), td('"We got copied" (só vale para a original)')]), tr([td('Tibatoes'), td('pré-venda de viagem, PDF de US$ 9,95'), td('promessa de TDAH e autismo, 250 itens')]), tr([td('Lovealotter'), td('gancho do interruptor, anúncio direto para a PDP'), td('"50% OFF - Today Only" permanente')]), tr([td('Montessori Paradise'), td('lista para avó no Natal'), td('"80K+ happy customers"')])]) + btn('Ver o blueprint', 'benchmark-visual.html', 'primary')) +
    sec('regua', '08', 'Régua de métricas', table(['Métrica', 'Benchmark', 'Meta do teste', 'Ação'], [tr([td(dfn('CPM')), td('US$ 10,42 (Meta e-commerce 2026)'), td('até A$ 25'), td('acima disso, abrir o público')]), tr([td('CTR do link'), td('referência de mercado ~1%'), td('≥ 1%'), td('abaixo de 0,8% com A$ 100: pausar')]), tr([td('Conversão da loja'), td('0,57% (IRP Baby & Child, piso) a 1,64% (Toys)'), td('≥ 1,5%'), td('abaixo: revisar página, prova de segurança e preço')]), tr([td(dfn('CPA')), td('10,92% da receita (IRP)'), td('≤ A$ 35'), td('acima de A$ 52: trocar criativo')]), tr([td('Devolução'), td(na('não publicado por nenhuma fonte')), td('≤ 5% dos pedidos'), td('acima: rever fornecedor e foto de escala')])])) +
    sec('suas', '09', 'As decisões que são suas', '<div class="grid g2"><div class="card"><span class="eyebrow a">verba</span><p>Teste mínimo de A$ 60/dia por 7 dias (~A$ 420 em anúncio, ~A$ 600 no total). Menos que isso não sai da fase de aprendizado. Dado + trade-off: menos verba = mais tempo para saber.</p></div><div class="card"><span class="eyebrow a">premissa culpada</span><p>Se der errado, a primeira suspeita é o CPA de A$ 35 (premissa, não medição), seguida do custo e da qualidade do fornecedor (estimados). Por isso o PDF e o busy book entram desde o dia 1, e a amostra com laudo vem antes de tudo.</p></div><div class="card"><span class="eyebrow a">risco consciente</span><p>Faturamento dos concorrentes não foi medido (SimilarWeb bloqueado). A decisão se apoia em anúncios longevos e na loja australiana crescendo, não em receita. Se quiser mais certeza, abra os 4 sites com a extensão do SimilarWeb antes de gastar.</p></div><div class="card"><span class="eyebrow a">responsabilidade</span><p>Quem vende brinquedo responde pela segurança dele na Austrália. O laudo do fornecedor e o teste de puxar não são burocracia: são o que te protege se algo der errado.</p></div></div>') +
    sec('checklist', '10', 'Checklist', '<ul class="check" data-key="wattlebee-plano">' + ['Pedir amostra a 2 fornecedores com laudo de segurança', 'Teste de puxar cada peça + tampa da pilha', 'Registrar domínio .com.au ou .com e loja Shopify', 'Subir 6 itens (build.json)', 'Criar o PDF de 30 atividades no Canva', 'Escrever a página "Our Safety Promise"', 'Filmar a amostra (criança concentrada + teste de puxar)', 'Gerar imagens com os prompts da tela 09', 'Escrever 3 anúncios (tela 04)', 'Configurar pixel e conversões', 'Ligar 3 anúncios a A$ 20/dia', 'Aplicar o critério de parada no dia 7'].map((t, i) => '<li><input type="checkbox" id="ck' + i + '"><label for="ck' + i + '">' + t + '</label><span class="who">você</span></li>').join('') + '</ul><div class="check-sum"></div>' + note('Loja montada não é loja pronta para vender: sem laudo, sem amostra testada e sem vídeo real da criança, não anuncie.', 'a')) +
    footer(false);
  return doc({ title: 'Plano de ação · Wattlebee', current: 'plano', screen: { code: '06', title: 'Plano de ação' }, body, next: { t: 'Pedir amostra do busy board a 2 fornecedores com laudo', s: 'dias 1 a 4', b: 'Abrir fornecedores', h: ALI(SOURCING['switch-busy-board'][0]), ext: true } });
}

/* ================= 07 CATALOGO ================= */
export function catalogo() {
  const card = p => '<article class="card product-deep"><div class="row"><div><span class="eyebrow g">' + esc(p.sku) + ' · ' + PAPEL[p.handle] + '</span><h3>' + esc(p.titulo) + '</h3></div>' + pill(p.handle === 'quiet-time-activity-cards' ? 'CRIAR NO CANVA' : 'AMOSTRA + LAUDO', 'a') + '</div><div class="stats mini">' + stat({ v: aud(+p.preco), l: 'preço proposto', d: p.de ? 'de ' + aud(+p.de) : 'sem preço "de"', k: 'rec' }) + stat({ v: esc(SOURCING[p.handle][1]), l: 'custo estimado', d: 'sem amostra', k: 'inf' }) + '</div>' +
    '<dl class="kv"><dt>Tipo</dt><dd>' + esc(p.tipo) + '</dd><dt>Coleção</dt><dd>' + esc(p.colecao) + '</dd><dt>Tags</dt><dd>' + esc(p.tags.join(', ')) + '</dd><dt>Eyebrow da PDP</dt><dd>' + esc(p.pdp.eyebrow) + '</dd><dt>Lede</dt><dd>' + esc(p.pdp.lede) + '</dd><dt>Proof</dt><dd>' + (p.pdp.proof ? esc(p.pdp.proof) : na('nenhuma citação real de cliente da marca ainda (loja nova)')) + '</dd><dt>Season</dt><dd>' + esc(p.pdp.season) + '</dd></dl>' +
    '<details><summary>Copy completa do produto</summary><div class="detail-body">' + p.descricao_html + '</div></details>' +
    '<details><summary>SEO e arquivos de referência</summary><dl class="kv"><dt>SEO title</dt><dd>' + esc(p.seo_titulo) + '</dd><dt>SEO description</dt><dd>' + esc(p.seo_descricao) + '</dd><dt>Referência visual</dt><dd>Referencia de imagens - cena e prompt/' + p.handle + '/</dd><dt>Product Master</dt><dd>' + na('amostra e fotos reais ainda não existem') + '</dd></dl></details></article>';
  const nRef = (build.referencias_produtos || []).reduce((a, r) => a + r.downloaded_carousel_count, 0);
  const body = pageHead({ eyebrow: '07 · execução · catálogo · oferta · conteúdo de loja', h1: 'Catálogo e <em>oferta</em> da Wattlebee', answer: 'Tudo o que vai para a loja: 6 itens com copy, SEO, coleções, menu e as 6 páginas institucionais no padrão real do mercado.', meta: ['fonte: dados/build.json', 'copy em inglês australiano (mercado AU)'] }) +
    toc([['resumo', 'Resumo'], ['oferta', 'Oferta'], ['produtos', 'Produtos'], ['colecoes', 'Coleções'], ['menu', 'Menu'], ['paginas', 'Páginas'], ['prontidao', 'Prontidão']]) +
    sec('resumo', '00', 'Resumo', '<div class="stats">' + stat({ v: build.produtos.length, l: 'itens (5 físicos + 1 digital)', k: 'rec' }) + stat({ v: build.colecoes.length, l: 'coleções', k: 'rec' }) + stat({ v: nRef, l: 'referências visuais baixadas', k: 'obs' }) + stat({ l: 'Product Masters aprovados', naWhy: '0: a amostra ainda não foi fotografada' }) + '</div>' + evidence({ fonte: 'build.json', obs: 'Busy board, PDF de atividades, busy book, kit, árvore de feltro e bolsa.', interp: 'Catálogo pequeno o bastante para um iniciante operar, com pico de Natal coberto.', dec: 'Pronto para o /montar-loja, exceto fotos e PDF.', next: 'Fechar fornecedor com laudo e criar o PDF.' })) +
    sec('oferta', '01', 'Escada de oferta', table(['Degrau', 'Item', { t: 'Preço', num: true }, 'Papel'], [tr([td('core'), td('Switch and Latch Busy Board'), td('A$ 69,95', 'num'), td('produto principal')]), tr([td('bump'), td('Quiet Time Activity Cards (PDF)'), td('A$ 9,95', 'num'), td('order bump na PDP')]), tr([td('upsell'), td('Travel Busy Book'), td('A$ 39,95', 'num'), td('no carrinho')]), tr([td('bundle'), td('Quiet Time Kit'), td('A$ 99,95', 'num'), td('kit de presente com frete grátis')])]) + note('Economia real do kit: A$ 24,90 mais barato que board + busy book + bolsa separados (A$ 124,85), e sem os A$ 9,95 de frete.', 'g')) +
    sec('produtos', '02', 'Produto por produto', '<div class="product-list">' + build.produtos.map(card).join('') + '</div>') +
    sec('colecoes', '03', 'Coleções', table(['Coleção', 'Handle', 'Descrição', { t: 'Produtos', num: true }], build.colecoes.map(c => tr([td(esc(c.titulo)), td('<span class="mono">' + c.handle + '</span>'), td(c.descricao_html), td(build.produtos.filter(p => p.colecao === c.handle).length, 'num')])))) +
    sec('menu', '04', 'Menu principal', table([{ t: '#', num: true }, 'Título', 'Tipo', 'Destino'], build.menu.map((m, i) => tr([td(i + 1, 'num'), td(esc(m.titulo)), td(m.tipo), td(m.handle ? '<span class="mono">' + m.handle + '</span>' : 'home')])))) +
    sec('paginas', '05', 'Páginas institucionais', note('Estado: rascunho. Prazo e troca no padrão observado nos concorrentes: preparo em 1 a 2 dias úteis e entrega em 6 a 12 dias úteis (Tibatoes e Lovealotter), frete de A$ 9,95 com grátis acima de A$ 99 (toddla.co cobra A$ 9,95; Tibatoes dá grátis acima de A$ 100), 30 dias de devolução (Tibatoes). A página "Our Safety Promise" não existe em nenhum concorrente: é a diferença.', 'b') + build.paginas.map(p => '<details class="legal"><summary>' + esc(p.titulo) + ' (' + p.handle + ')</summary><div class="detail-body">' + p.corpo_html + '</div></details>').join('')) +
    sec('prontidao', '06', 'Prontidão por produto', table(['Produto', 'Papel', 'Referências', 'Product Master', 'Estado'], build.produtos.map(p => tr([td(esc(p.titulo)), td(PAPEL[p.handle]), td('carrossel baixado ' + nat('obs')), td(na(p.handle === 'quiet-time-activity-cards' ? 'PDF ainda não criado' : 'sem amostra')), td(pill(p.handle === 'quiet-time-activity-cards' ? 'criar PDF' : 'aguarda amostra + laudo', 'a'))]))) + note('Handoff para o /montar-loja: build.json pronto (copy, preço, coleções, menu, páginas, prompts). Falta a foto real dos produtos, o laudo do fornecedor escolhido e o arquivo do PDF.', 'g')) +
    footer(false);
  return doc({ title: 'Catálogo e oferta · Wattlebee', current: 'catalogo', screen: { code: '07', title: 'Catálogo e oferta' }, body, next: { t: 'Fechar fornecedor com laudo de segurança', b: 'Ver plano', h: 'plano-de-acao.html' } });
}

/* ================= 08 BENCHMARK ================= */
export function benchmark() {
  const top = MAIN4;
  const LEIT = { toddla: ['copiar: criança real nas fotos + bundle', 'evitar: "We got copied"'], tibatoes: ['copiar: pré-venda por público', 'evitar: catálogo de 250 itens'], lovealotter: ['copiar: gancho do interruptor', 'evitar: "50% OFF - Today Only" fixo'], paradise: ['copiar: lista para avó', 'evitar: "80K+ happy customers"'] };
  const cmp = (tipo) => '<div class="compare">' + top.map(l => '<div class="c"><div class="h"><b>' + esc(l.nome) + '</b>' + pill(l.veredito, VER_CLS[l.veredito]) + '</div><div class="screen ' + (tipo.endsWith('m') ? 'mob' : 'desk') + '"><img loading="lazy" src="prints/' + l.slug + '-' + (tipo.startsWith('home') ? 'home' : 'pdp') + '.jpg" alt="' + esc(l.nome + ' ' + tipo) + '"></div><div class="f"><b>' + esc(l.nome) + '</b><span class="m">' + LEIT[l.slug][0] + '</span><span class="e">' + LEIT[l.slug][1] + '</span></div></div>').join('') +
    '<div class="c ours"><div class="h"><b>Nossa Wattlebee</b>' + pill('blueprint', 'g') + '</div><div class="screen ' + (tipo.endsWith('m') ? 'mob' : 'desk') + '"><iframe src="mockup-' + (tipo.startsWith('home') ? 'home' : 'pdp') + '.html" title="Wattlebee" loading="lazy" style="width:100%;height:100%;border:0"></iframe></div><div class="f"><b>Prova de segurança + sossego</b><span class="m">melhoria: teste de puxar e pilha parafusada na dobra</span></div></div></div>';
  const bp = '<section class="blk" id="blueprint"><h2><span class="n">09</span>Blueprint da sua loja <span class="eyebrow g" style="margin-left:8px">monte a SUA assim</span></h2><p class="lead">A planta visual da SUA loja: a home e a página de produto já desenhadas na identidade da marca <b>Wattlebee</b>, com a copy em inglês australiano nos lugares certos. É o layout para reproduzir no Shopify.</p><div class="note"><b>Como ler.</b> Os blocos com fundo claro e um rótulo no canto (ex: "IMAGEM 2 · prova de segurança") são onde entram as imagens. Textos, botões, preço e PDF como item extra já estão no lugar final. A copy está em inglês, idioma do mercado.</div>' +
    '<div class="bpv"><h3>1 · Layout desktop <small style="color:var(--low);font-weight:400">· Home à esquerda, página de produto à direita</small></h3><p class="cap">Como as duas páginas ficam no computador. É o mesmo site: o que muda no celular é só o empilhamento dos blocos. Role dentro de cada janela para ver a página inteira.</p><div class="bprow"><div class="bpcol"><div class="browser"><div class="bar"><span class="dot"></span><span class="dot"></span><span class="dot"></span><span class="url">wattlebee.com.au</span></div><div class="shotf desk" data-base="1280"><iframe src="mockup-home.html" title="Home desktop" loading="lazy"></iframe></div></div><div class="bplbl">Home &nbsp;·&nbsp; <a href="mockup-home.html" target="_blank">tela cheia ↗</a></div></div><div class="bpcol"><div class="browser"><div class="bar"><span class="dot"></span><span class="dot"></span><span class="dot"></span><span class="url">wattlebee.com.au/products/switch-busy-board</span></div><div class="shotf desk" data-base="1280"><iframe src="mockup-pdp.html" title="PDP desktop" loading="lazy"></iframe></div></div><div class="bplbl">Página de produto &nbsp;·&nbsp; <a href="mockup-pdp.html" target="_blank">tela cheia ↗</a></div></div></div>' +
    '<h3 style="margin-top:24px">2 · Layout celular <span class="eyebrow g" style="margin-left:8px">a prioridade: 90% do tráfego é mobile</span></h3><p class="cap">É <b>aqui</b> que o layout tem que estar impecável. 9 em cada 10 clientes veem a loja assim, no celular. Desenhe pensando primeiro nesta tela; o desktop é a consequência.</p><div class="bprow"><div class="bpcol"><div class="phone"><div class="shotf" data-base="390"><iframe src="mockup-home.html" title="Home celular" loading="lazy"></iframe></div></div><div class="bplbl">Home &nbsp;·&nbsp; <a href="mockup-home.html" target="_blank">tela cheia ↗</a></div></div><div class="bpcol"><div class="phone"><div class="shotf" data-base="390"><iframe src="mockup-pdp.html" title="PDP celular" loading="lazy"></iframe></div></div><div class="bplbl">Página de produto &nbsp;·&nbsp; <a href="mockup-pdp.html" target="_blank">tela cheia ↗</a></div></div></div></div>' +
    '<div class="note g"><b>A ordem dos blocos não é estética, é psicológica.</b> Home: promessa ("the switches they\'re actually allowed to touch") → prova de segurança (puxar, pilha parafusada) → sossego (café quente) → kit de presente → avaliações reais. PDP: galeria com prova → preço → PDF como item extra → objeções (solta? enjoa? barulho?) → garantia → botão fixo no rodapé do celular, porque quem rola até as objeções precisa comprar sem voltar ao topo.</div></section>';
  const nRef = (build.referencias_produtos || []).reduce((a, r) => a + r.downloaded_carousel_count, 0);
  const PESO = { toddla: '777 KB', tibatoes: '603 KB', lovealotter: '653 KB', paradise: '1.095 KB', clevertoys: '809 KB' };
  const body = pageHead({ eyebrow: '08 · execução · loja · benchmark visual responsivo + blueprint', h1: 'Como a <em>sua loja</em> fica melhor que as 4', answer: 'Comparando home e página de produto das 4 lojas mais fortes, a Wattlebee pega as fotos com criança real e o bundle da toddla.co, o gancho do interruptor da Lovealotter, a lista de presente da Montessori Paradise, e acrescenta o que nenhuma mostra: a prova de segurança em imagem.', meta: ['15 prints reais (Playwright)', 'mockups desktop 1280 e celular 390'] }) +
    toc([['porque', 'Por que estas 4'], ['home-d', 'Home desktop'], ['home-m', 'Home celular'], ['pdp-d', 'PDP desktop'], ['pdp-m', 'PDP celular'], ['leitura', 'Leitura'], ['perf', 'Carregamento'], ['imagens', 'Imagens'], ['blueprint', 'Blueprint'], ['validar', 'Validar']]) +
    sec('porque', '01', 'Por que estas 4', '<div class="grid g4">' + top.map(l => stat({ v: n(l.ativos, 0), l: esc(l.nome) + ': anúncios ativos', d: esc(l.momento.split(':')[0]), k: 'obs' })).join('') + '</div>' + note('Critério: sinal de escala medido (anúncios ativos + longevidade do campeão), não gosto visual. A Clever Toys Box (19 ativos) ficou fora da comparação visual.', 'b')) +
    sec('home-d', '02', 'Home · desktop', cmp('home-d')) + sec('home-m', '03', 'Home · celular', cmp('home-m') + note('Os prints foram capturados em 1280px; no celular, veja a moldura do blueprint (390px reais).', 'a')) +
    sec('pdp-d', '04', 'Página de produto · desktop', cmp('pdp-d')) + sec('pdp-m', '05', 'Página de produto · celular', cmp('pdp-m')) +
    sec('leitura', '06', 'Leitura de design, oferta e UX ' + nat('inf'), table(['Critério', 'toddla.co', 'Tibatoes', 'Lovealotter', 'Montessori Paradise', '<b>Nossa direção</b>'], [
      tr([td('Promessa acima da dobra'), td('a marca de brinquedo sem tela'), td('o brinquedo sem tela que toda criança precisa'), td('Montessori para o desenvolvimento'), td('liquidação até 50%'), td('<b>the switches they\'re allowed to touch</b>')]),
      tr([td('Preço e âncora'), td('US$ 39,99 de US$ 79,98'), td('US$ 50,60 de US$ 67,48'), td('US$ 40,98 de US$ 80,98'), td('US$ 36,97 de US$ 49,97'), td('<b>A$ 69,95 + kit A$ 99,95</b>')]),
      tr([td('Item extra'), td('bundles de US$ 49,99 a US$ 149,99'), td('PDF de US$ 9,95, Upcart'), td('não visto'), td('código EXTRA10'), td('<b>PDF de A$ 9,95 na PDP + busy book no carrinho</b>')]),
      tr([td('Prova'), td('"11.000 reviews" (não verificável) + UGC'), td('"9.869 reviews" (~100 verificáveis)'), td('Judge.me sem contagem'), td('"80K+ happy customers" (loja de 9 meses)'), td('<b>teste de puxar + pilha parafusada + reviews reais só depois das vendas</b>')]),
      tr([td('Segurança'), td('não mostrada'), td('não mostrada'), td('não mostrada'), td('não mostrada'), td('<b>página "Our Safety Promise" + imagem 2 da galeria</b>')]),
    ])) +
    sec('perf', '07', 'Carregamento observado', table(['Loja', 'Peso do print da home', 'Observação'], LOJAS.map(l => tr([td(esc(l.nome)), td(PESO[l.slug]), td('home, PDP e carrinho capturados sem erro')]))) + note('É laboratório (Playwright, uma visita), não Core Web Vitals de campo. Tempo de carregamento, DCL e número de recursos ' + na('o prints.js não mede esses tempos') + '. O peso do print indica o tamanho visual da página (a Montessori Paradise é a mais longa).', 'a')) +
    sec('imagens', '08', 'Auditoria de imagens', '<div class="grid g4">' + stat({ v: nRef, l: 'imagens de carrossel baixadas', k: 'obs' }) + stat({ v: (build.referencias_produtos || []).length, l: 'produtos com referência', k: 'obs' }) + stat({ v: '1 a 16', l: 'faixa de imagens por PDP', k: 'obs' }) + stat({ v: '0', l: 'imagens de prova de segurança', d: 'a brecha', k: 'inf' }) + '</div>' +
      table(['Produto', 'Concorrente', { t: 'Carrossel real', num: true }, { t: 'Baixadas', num: true }, 'Status'], (build.referencias_produtos || []).map(r => tr([td(esc(r.product_name)), td(esc(r.competitor)), td(r.real_carousel_count, 'num'), td(r.downloaded_carousel_count, 'num'), td(pill(r.amostrado ? 'amostrado' : 'completo', 'b'))]))) + note('Método: carrosseis.mjs baixou o carrossel da PDP do concorrente campeão de cada produto. O PDF da Tibatoes tem carrossel real de 1 imagem.', 'b')) +
    bp +
    sec('validar', '10', 'Validar', '<div class="grid g2"><div class="card"><span class="eyebrow a">antes de construir</span><p>Amostra na mão, laudo do fornecedor e teste de puxar feitos; só então filmar e gerar imagens.</p></div><div class="card"><span class="eyebrow a">antes de escalar</span><p>30 vendas com CPA ≤ A$ 35 e menos de 5% de devolução.</p></div></div>' + note('O blueprint melhora a chance de conversão, mas conversão só se mede com tráfego real.', 'b')) +
    footer(false);
  return doc({ title: 'Loja: benchmark e blueprint · Wattlebee', current: 'benchmark', screen: { code: '08', title: 'Loja: benchmark e blueprint' }, body, next: { t: 'Montar home e PDP mobile-first conforme o blueprint', b: 'Ver mockup da PDP', h: 'mockup-pdp.html' } });
}

/* ================= 09 IDENTIDADE ================= */
export function identidade() {
  const logos = build.identidade_visual.logos;
  const NOMES = { wordmark: 'Wordmark / logo', icone_perfil: 'Ícone / favicon', capa_loja: 'Capa / banner da loja', capa_facebook: 'Capa de rede social' };
  const rp = build.referencias_produtos || [];
  const nRef = rp.reduce((a, r) => a + r.downloaded_carousel_count, 0);
  const tabs = '<div role="tablist" aria-label="Produtos" data-hash>' + rp.map((r, i) => '<button class="tab" role="tab" aria-selected="' + (i === 0) + '" aria-controls="prod-' + r.product_handle + '"><span>' + esc(r.product_name) + '</span><small>' + r.downloaded_carousel_count + ' imagens · ' + esc(r.competitor) + '</small></button>').join('') + '</div>' +
    rp.map((r, i) => '<div class="panel" id="prod-' + r.product_handle + '" role="tabpanel"' + (i ? ' hidden' : '') + '><div class="card" style="margin-bottom:12px"><span class="eyebrow b">carrossel ' + (r.amostrado ? 'amostrado' : 'completo') + ' · ' + r.downloaded_carousel_count + ' de ' + r.real_carousel_count + '</span><h3 style="margin:6px 0 4px">' + esc(r.product_name) + ' (' + PAPEL[r.product_handle] + ')</h3><p>Referência de cena: ' + esc(r.competitor) + '. Cada arquivo tem seu prompt; anexe junto com as fotos reais da amostra Wattlebee.' + (r.product_handle === 'quiet-time-activity-cards' ? ' Nota: produto digital; o carrossel real do concorrente tem 1 imagem. Gere também um mockup dos cartões impressos ao lado do busy board (posição 7 da sequência).' : '') + (r.product_handle === 'quiet-time-kit' ? ' Nota: o kit é sintético (board + busy book + bolsa); use as referências do board e do busy book como produto, e esta pasta só como cena de bundle.' : '') + '</p></div><div class="grid g3">' +
      r.references.map(x => imgcard({ num: String(x.position).padStart(2, '0'), title: x.type, what: esc(x.description), img: '../' + x.reference_file, ref: 'Arquivo: ' + esc(x.reference_file), prompt: x.prompt })).join('') + '</div></div>').join('');
  const banners = build.imagens_pdp.sequencia.filter(s => s.tipo === 'banner_home');
  const body = pageHead({ eyebrow: '09 · execução · identidade e imagens', h1: 'O <em>kit visual</em> da Wattlebee', answer: 'Paleta, 4 prompts de marca, 2 banners e um prompt por imagem de referência para todos os 6 itens da escada de oferta.', meta: [nRef + ' referências baixadas', '4 prompts de marca', 'prompts em inglês, 5 blocos'] }) +
    toc([['como', 'Como usar'], ['paleta', 'Paleta'], ['logos', 'Identidade de marca'], ['banners', 'Banners'], ['sequencia', 'Sequência da PDP'], ['carrosseis', 'Carrosséis por produto']]) +
    sec('como', '00', 'Como usar', '<ol class="steps"><li>Escolha a posição da imagem (tabela da seção 04).</li><li>Localize o arquivo de referência na pasta "Referencia de imagens - cena e prompt".</li><li>Anexe a referência de cena + as fotos reais da amostra.</li><li>Copie o prompt (botão Copiar).</li><li>Cole no gerador de imagem.</li><li>Confira: produto igual à amostra (interruptores, trincos e zíper no lugar certo), sem logo de concorrente.</li></ol>' + note('Hierarquia: a referência manda na CENA; a foto real da amostra (Product Master) manda no PRODUTO. As imagens de prova (teste de puxar, criança concentrada) devem ser vídeo e foto reais, não geradas: prova gerada por IA não prova nada.', 'b') + note('Status: REFERÊNCIA PENDENTE para o produto até a amostra existir. Os prompts já estão prontos.', 'a')) +
    sec('paleta', '01', 'Paleta e fontes', swatches(PALETA) + '<p style="margin-top:10px">Títulos: <b>Quicksand</b> negrito (handle quicksand_n7). Texto: <b>Nunito Sans</b> (nunito_sans_n4). Voz: calma, prática, de quem tem criança pequena em casa; nada de "genius baby" nem neon.</p>') +
    sec('logos', '02', 'Identidade de marca', '<div class="grid g2">' + logos.map((l, i) => imgcard({ num: String(i + 1).padStart(2, '0'), title: NOMES[l.tipo], what: esc(l.descricao), ref: 'Sem referência externa: gerado da identidade da marca', prompt: l.prompt })).join('') + '</div>') +
    sec('banners', '03', 'Banner da home (desktop e celular)', '<div class="grid g2">' + banners.map((b, i) => imgcard({ num: 'B' + (i + 1), title: b.formato === 'banner_desktop' ? 'Banner desktop 1920x1080' : 'Banner celular 1080x1350', what: esc(b.descricao), ref: 'Referência de cena: carrossel do busy board (Lovealotter)', prompt: 'REFERENCE HIERARCHY\n' + b.prompt.split('\n\n').slice(1, 2).join('') + '\n\nART DIRECTION\n' + b.prompt.split('\n\n').slice(2, 5).join(' ') + '\n\nPRODUCT FIDELITY\nThe Wattlebee Switch and Latch Busy Board: natural wooden board with rocker and toggle light switches with small LEDs, a gate latch, a zip panel and a turning dial, all screwed on. Use the real sample photos as the only authority.\n\nBRAND AND LEGAL CLEANUP\nNo text, no logos, no competitor names or watermarks.\n\nQUALITY CONTROL\n' + b.prompt.split('\n\n').slice(-1)[0] })).join('') + '</div>') +
    sec('sequencia', '04', 'Sequência de imagens', table([{ t: '#', num: true }, 'Tipo', 'Produto', 'Descrição', 'Referência de cena', 'Status'], build.imagens_pdp.sequencia.map(s => tr([td(s.posicao, 'num'), td(s.tipo), td(s.produto_handle || '-'), td(esc(s.descricao)), td(s.referencia_cena_arquivo || 'pasta do produto'), td(pill(s.status, 'a'))]))) + note('Achado da auditoria de carrossel: ' + esc(build.imagens_pdp.achado) + ' Faixa do nicho: ' + build.imagens_pdp.faixa_nicho.min + ' a ' + build.imagens_pdp.faixa_nicho.max + ' imagens por PDP.', 'g')) +
    sec('carrosseis', '05', 'Carrosséis completos por produto', tabs) +
    footer(false);
  return doc({ title: 'Identidade e imagens · Wattlebee', current: 'identidade', screen: { code: '09', title: 'Identidade e imagens' }, body, next: { t: 'Filmar a amostra real antes de gerar qualquer imagem', b: 'Ver plano', h: 'plano-de-acao.html' } });
}

/* ================= 10 DADOS ================= */
export function dadosFontes() {
  const nRef = (build.referencias_produtos || []).reduce((a, r) => a + r.downloaded_carousel_count, 0);
  const arq = [['radar-subnichos.json', 'Meta Ads (radar de 9 sementes + 3 candidatos)', 'Mercados'], ['mcp-contagens.json', 'Meta Ads (48 consultas, Montessori)', 'Mercados, Demanda, Central'], ['descartado-carregador/mcp-contagens.json', 'Meta Ads (48 consultas, carregador, descartado)', 'Mercados'], ['demanda-contagens.json', 'Meta Ads (18 termos, AU)', 'Demanda'], ['autocomplete.json', 'autocomplete Google + Bing (527 termos)', 'Demanda'], ['matriz-paises.json', 'biblioteca-api.mjs matriz', 'Mercados'], ['mineracao-2026-10-06-15-35.json', 'Biblioteca pública, ' + n(MIN, 0) + ' anúncios', 'Criativos'], ['mineracao-montessori-filtrada.json', n(FILTRADOS, 0) + ' anúncios do nicho, sem ruído', 'Criativos, swipe'], ['escala-2026-10-06-15-35.json', 'ranking de escala por marca', 'Criativos, Concorrentes'], ['midia-por-loja.json', 'contagem e ritmo por page_id', 'Concorrentes, fichas'], ['dados-brutos.json', 'coletar.mjs (5 lojas finais)', 'fichas'], ['dados-brutos-lote1.json', 'coletar.mjs (8 lojas da triagem)', 'triagem'], ['reviews.json', 'reviews.mjs (JSON-LD)', 'fichas, Concorrentes'], ['trafego/trafego-similarweb.json', 'SimilarWeb (bloqueado)', 'fichas (lacuna)'], ['gads-transparency.json', 'Google Ads Transparency', 'fichas'], ['benchmark-setor.json', 'IRP Commerce ago/2026 (Baby & Child)', 'Economia, fichas'], ['voz-mercado.json', 'WebSearch (reviews, guias, recall)', 'Demanda, Estratégia'], ['build.json', 'decisões da Fase 5', 'Plano, Catálogo, Identidade'], ['auditoria-anuncios.json', 'ficha x Biblioteca', 'Concorrentes, Método'], ['swipe/anuncios.html', 'swipe.js (' + n(FILTRADOS, 0) + ' anúncios)', 'Criativos']];
  const body = pageHead({ eyebrow: '10 · apoio · dados, fontes e artefatos', h1: 'De onde veio <em>cada número</em>', answer: 'Inventário dos arquivos-fonte, cobertura da extração, auditoria de contagem e as lacunas com o impacto de cada uma.', meta: ['nada foi publicado', 'pasta local'] }) +
    toc([['inventario', 'Inventário'], ['cobertura', 'Cobertura'], ['volume', 'Volume'], ['auditoria', 'Auditoria'], ['lacunas', 'Lacunas'], ['estado', 'Estado']]) +
    sec('inventario', '01', 'Inventário de arquivos-fonte', table(['Arquivo', 'Origem', 'Onde aparece'], arq.map(([a, b, c]) => tr([td('<a href="../dados/' + a + '">' + esc(a) + '</a>'), td(b), td(c)])))) +
    sec('cobertura', '02', 'Cobertura da extração', '<div class="grid g4">' + stat({ v: n(MIN, 0), l: 'anúncios extraídos', d: '9 buscas, EUA, ativos', k: 'obs' }) + stat({ v: n(FILTRADOS, 0), l: 'do nicho (depois do filtro)', d: '49 marcas de brinquedo', k: 'obs' }) + stat({ v: '1.495/1.512', l: 'anúncios com domínio de destino', k: 'obs' }) + stat({ v: '1/1.512', l: 'com gasto/impressões', d: 'a Meta não publica', k: 'obs' }) + '</div>' + note('A extração foi feita nos EUA (onde estão a maioria dos anúncios do nicho); o país-alvo (Austrália) foi medido pelo conector, termo a termo. Os ' + n(MIN, 0) + ' anúncios (até 200 por busca, os mais recentes) são uma amostra por recência. ' + n(MIN - FILTRADOS, 0) + ' anúncios de ruído foram retirados antes da galeria e do swipe.', 'b')) +
    sec('volume', '03', 'Volume da entrega', table(['Item', { t: 'Quantidade', num: true }], [tr([td('Telas'), td('12 + 5 fichas', 'num')]), tr([td('Prints de loja'), td('15', 'num')]), tr([td('Criativos baixados'), td('10', 'num')]), tr([td('Imagens de referência'), td(nRef, 'num')]), tr([td('Prompts de imagem'), td(nRef + ' + 4 de marca + 2 banners', 'num')])])) +
    sec('auditoria', '04', 'Auditoria de contagem de anúncios', table(['Loja', 'page_id', { t: 'Ativos', num: true }, { t: 'Histórico', num: true }, 'Método', 'Resultado'], LOJAS.map(l => tr([td(esc(l.nome)), td('<span class="mono">' + l.pageIds.join(', ') + '</span>'), td(n(l.ativos, 0), 'num'), td(n(l.historico, 0), 'num'), td('domínio'), td(pill('ok', 'g'))])))) +
    sec('lacunas', '05', 'Lacunas e impacto', table(['Lacuna', 'Motivo', 'Impacto na decisão'], [tr([td('Visitas e faturamento das lojas'), td('SimilarWeb bloqueou (CloudFront); extensão manual recusada'), td('tamanho das lojas lido por anúncios; faturamento só da Paradise, "estimado incerto"; não muda o veredito, mas reduz a certeza')]), tr([td('Custo do fornecedor'), td('sem amostra; preço só do trecho de busca'), td('a margem pode ser maior ou menor; por isso a amostra é o passo 1')]), tr([td('Laudo de segurança do fornecedor'), td('depende da conversa com o fornecedor'), td('bloqueio real: sem laudo, não anunciar')]), tr([td('Benchmark do setor na Austrália'), td('IRP publica lojas do Reino Unido'), td('conversão e CPA% do setor usados como ordem de grandeza')]), tr([td('Capa e transcrição dos vídeos'), td('ffmpeg e whisper ausentes'), td('capa veio da prévia da Biblioteca; leitura pela copy')]), tr([td('Contagem de termos com palavras comuns'), td('a Biblioteca busca palavras soltas'), td('termos marcados com ruído alto servem só como ordem de grandeza')])])) +
    sec('estado', '06', 'Estado do pacote', note('Nada foi publicado: a entrega mora só nesta pasta local. Nenhum dado foi enviado a GitHub, hub ou site.', 'g')) +
    footer(false);
  return doc({ title: 'Dados e fontes · Montessori', current: 'dados', screen: { code: '10', title: 'Dados, fontes e artefatos' }, body, next: { t: 'Ver os limites da análise', b: 'Método', h: 'metodo.html' } });
}

/* ================= 11 METODO ================= */
export function metodo() {
  const dic = Object.entries(S.GLOSS).map(([k, v]) => '<dt>' + esc(k) + '</dt><dd>' + esc(v) + '</dd>').join('');
  const body = pageHead({ eyebrow: '11 · apoio · método, limites e auditoria', h1: 'Como esta pesquisa foi <em>feita</em>', answer: 'A régua, as fontes, o que cada uma não entrega, o que não foi obtido e o dicionário dos termos.', meta: ['/raio-x · Fases 0 a 8'] }) +
    toc([['regua', 'Régua'], ['caminho', 'Caminho da pesquisa'], ['fontes', 'Fontes'], ['honestidade', 'Honestidade'], ['revisao', 'Revisão'], ['dicionario', 'Dicionário rápido']]) +
    sec('regua', '01', 'A régua da entrega', legendNat() + note('Observado = visto na fonte. Calculado = conta declarada a partir do observado. Inferido = leitura do analista. Recomendado = ação sugerida. Não obtido = a fonte não entregou, sempre com motivo.', 'b')) +
    sec('caminho', '02', 'Caminho da pesquisa', '<ol class="steps"><li><b>Radar:</b> 9 sementes de Baby &amp; Parenting nos EUA e 3 candidatos (carregador, Montessori, alimentação) em 8 países. Você escolheu carregador.</li><li><b>Carregador descartado:</b> produto regulado nos EUA (ASTM F2236 + certificado CPC), com recall e alerta de risco de queda. Você escolheu trocar para Montessori. Os dados do carregador ficaram em dados/descartado-carregador.</li><li><b>Montessori:</b> matriz de 8 países, 1.512 anúncios extraídos, 13 lojas triadas, 5 fichas completas (só dropship).</li><li><b>Tráfego:</b> SimilarWeb bloqueado; você escolheu seguir pelo proxy.</li></ol>') +
    sec('fontes', '03', 'Fontes e o que cada uma não entrega', table(['Fonte', 'Entrega', 'Não entrega'], [tr([td('Conector Meta Ads'), td('contagem exata por termo, país, página'), td('copy completa, criativo, gasto; a busca casa palavras soltas')]), tr([td('Biblioteca pública (minerar.js)'), td('copy, criativo, destino, datas'), td('gasto e impressões; amostra é por recência')]), tr([td('SimilarWeb público'), td('visitas, rejeição, países'), td('nesta coleta: nada (bloqueado)')]), tr([td('products.json'), td('catálogo, preços, datas'), td('vendas por produto')]), tr([td('reviews.mjs (JSON-LD)'), td('contagem verificada de reviews por produto'), td('total da loja; reviews importados')]), tr([td('Google Ads Transparency'), td('se a loja anuncia no Google'), td('volume real de anúncios')]), tr([td('IRP Commerce'), td('conversão e CPA% do setor Baby & Child'), td('dados da Austrália; o ticket do setor é distorcido por carrinho e berço')]), tr([td('Autocomplete Google e Bing'), td('o que as pessoas digitam, em ordem'), td('volume mensal de busca')])])) +
    sec('honestidade', '04', 'Regras de honestidade', '<ul class="cl"><li>Anúncio ativo não prova lucro, só que alguém paga para manter.</li><li>Contagem por palavra-chave não é tamanho exato do mercado.</li><li>Alegação de marketing ("11.000 reviews", "9.869 reviews", "80K+ happy customers") não serve de base para estimativa.</li><li>Ausência de dado não é zero.</li><li>Isto não é aconselhamento jurídico sobre segurança de brinquedo: confirme com o fornecedor e com a ACCC.</li></ul>') +
    sec('revisao', '05', 'Revisão de qualidade', note('Rodados os revisores da skill (revisar, consistência, responsivo, auditoria de anúncios, telas) e a banca por página. Resultado em dados/julgamento.json.', 'b')) +
    sec('dicionario', '06', 'Dicionário rápido', '<dl class="kv">' + dic + '</dl>') +
    footer(false);
  return doc({ title: 'Método · Montessori', current: 'metodo', screen: { code: '11', title: 'Método, limites e auditoria' }, body, next: { t: 'Voltar à decisão', b: 'Central', h: '../Pesquisa%20-%20clique%20aqui.html' } });
}

/* ================= MOCKUPS ================= */
const MK_CSS = '<style>*{box-sizing:border-box;margin:0;padding:0}body{font-family:"Nunito Sans",system-ui,sans-serif;background:#FBF8F1;color:#2A2A26}h1,h2,h3{font-family:Quicksand,"Nunito Sans",system-ui,sans-serif;font-weight:700;color:#3F5E4E;letter-spacing:-.01em}.wrap{max-width:1200px;margin:0 auto;padding:0 20px}.ann{background:#3F5E4E;color:#FBF8F1;text-align:center;font-size:13px;padding:8px}.nav{display:flex;justify-content:space-between;align-items:center;padding:16px 20px;border-bottom:1px solid #E4DCCB}.logo{font-family:Quicksand,sans-serif;font-weight:700;letter-spacing:.08em;font-size:21px;color:#3F5E4E}.ph{background:#F3ECDD;border:1px dashed #E3A82B;display:flex;align-items:flex-end;justify-content:flex-start;color:#6b6656;font-size:12px;padding:10px;min-height:220px;border-radius:14px}.btn{display:inline-block;background:#E3A82B;color:#2A2A26;padding:14px 26px;border-radius:999px;text-decoration:none;font-size:15px;font-weight:800}.sec{padding:48px 0}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:18px}.card{background:#fff;border:1px solid #E4DCCB;border-radius:14px;padding:16px}.price{font-size:26px;color:#3F5E4E;font-weight:800}.price s{color:#9a937f;font-size:16px;margin-left:8px;font-weight:400}.tag{color:#C9704E;text-transform:uppercase;letter-spacing:.12em;font-size:12px;font-weight:800}.sticky{position:sticky;bottom:0;background:#FBF8F1;border-top:1px solid #E4DCCB;padding:12px 20px;display:flex;justify-content:space-between;align-items:center}@media(max-width:700px){.hero{grid-template-columns:1fr!important}.pdp{grid-template-columns:1fr!important}h1{font-size:32px!important}}</style>';
export function mockupHome() {
  return '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Wattlebee · Home</title>' + MK_CSS + '</head><body>' +
    '<div class="ann">Free shipping across Australia over $99 · 30-day happy-play guarantee · No button batteries</div><div class="nav"><span>Shop</span><span class="logo">WATTLEBEE</span><span>Cart (0)</span></div>' +
    '<!-- BLOCO: hero --><section class="sec"><div class="wrap hero" style="display:grid;grid-template-columns:1fr 1fr;gap:30px;align-items:center"><div><p class="tag">Montessori busy board · ages 1 to 3</p><h1 style="font-size:48px;margin:10px 0">The switches they\'re actually allowed to touch.</h1><p style="margin-bottom:20px">Light switches, latches, a zip and a dial on one solid wooden board. They flick, open and turn. You finish your coffee while it\'s still hot.</p><a class="btn" href="mockup-pdp.html">Shop the busy board · $69.95</a></div><div class="ph" style="min-height:380px">IMAGEM 0 · banner_home: toddler on the rug flicking switches, mum with coffee in soft focus</div></div></section>' +
    '<!-- BLOCO: trust-bar --><section style="background:#F3ECDD;padding:18px 0"><div class="wrap grid" style="text-align:center;font-size:14px"><span>Every part screwed on, pull-tested</span><span>AA batteries behind a screw</span><span>Screen-free, no loud sounds</span><span>30-day guarantee</span></div></section>' +
    '<!-- BLOCO NOVO: prova-seguranca (nao existe na biblioteca de blocos) --><section class="sec"><div class="wrap hero" style="display:grid;grid-template-columns:1fr 1fr;gap:30px;align-items:center"><div class="ph" style="min-height:320px">IMAGEM 2 · prova_seguranca: adult hand pulling a switch that stays put + screw on the battery cover</div><div><h2 style="font-size:34px;margin-bottom:12px">We pull every switch before it ships.</h2><p>Busy boards that shed knobs have been recalled. Ours are screwed through the board, not glued, and the battery box only opens with a screwdriver. No button batteries, anywhere.</p><p style="margin-top:10px"><a href="#" style="color:#3F5E4E;font-weight:800">Read our safety promise →</a></p></div></div></section>' +
    '<!-- BLOCO: sossego --><section class="sec" style="background:#fff"><div class="wrap"><h2 style="font-size:30px;margin-bottom:20px;text-align:center">Twenty quiet minutes, no screen</h2><div class="grid">' + ['Flick · light switches with tiny LEDs', 'Open · a real gate latch and a zip', 'Turn · a dial and a spinning gear'].map((t, i) => '<div class="card"><div class="ph" style="min-height:180px">IMAGEM 3.' + (i + 1) + '</div><p style="margin-top:10px;font-weight:700">' + t + '</p></div>').join('') + '</div></div></section>' +
    '<!-- BLOCO: shop-the-set --><section class="sec"><div class="wrap"><h2 style="font-size:32px;margin-bottom:20px;text-align:center">Quiet time, at home and on the go</h2><div class="grid">' + ['Switch and Latch Busy Board · $69.95', 'Travel Busy Book · $39.95', 'Quiet Time Kit · $99.95', 'Toddler Felt Christmas Tree · $44.95'].map((t, i) => '<div class="card"><div class="ph" style="min-height:200px">IMAGEM ' + [1, 4, 5, 6][i] + '</div><p style="margin-top:10px">' + t + '</p></div>').join('') + '</div></div></section>' +
    '<!-- BLOCO: reviews --><section class="sec" style="background:#fff"><div class="wrap"><h2 style="font-size:32px;text-align:center;margin-bottom:20px">From Wattlebee families</h2><p style="text-align:center;color:#6b6656">[Reviews and photos from real Wattlebee customers go here after the first orders. Do not import reviews from other stores.]</p></div></section>' +
    '<!-- BLOCO: fecho --><section class="sec" style="background:#3F5E4E;color:#FBF8F1;text-align:center"><h2 style="color:#FBF8F1;font-size:34px;margin-bottom:16px">Busy hands. Quiet house.</h2><a class="btn" href="mockup-pdp.html">Shop now</a></section></body></html>';
}
export function mockupPdp() {
  return '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Wattlebee · Switch and Latch Busy Board</title>' + MK_CSS + '</head><body>' +
    '<div class="ann">Free shipping across Australia over $99 · 30-day happy-play guarantee · No button batteries</div><div class="nav"><span>Shop</span><span class="logo">WATTLEBEE</span><span>Cart (0)</span></div>' +
    '<section class="sec"><div class="wrap pdp" style="display:grid;grid-template-columns:1.1fr 1fr;gap:34px">' +
    '<!-- BLOCO: galeria --><div><div class="ph" style="min-height:440px">IMAGEM 1 · still_produto: busy board on cream, switches lit</div><div class="grid" style="grid-template-columns:repeat(4,1fr);margin-top:10px">' + [2, 3, 7, 8].map(i => '<div class="ph" style="min-height:90px">IMG ' + i + '</div>').join('') + '</div></div>' +
    '<div><!-- BLOCO: prova-social --><p style="color:#6b6656;font-size:13px">[Star rating appears here only after the first real Wattlebee reviews]</p><!-- BLOCO: lede --><p class="tag" style="margin-top:8px">The switches they are allowed to touch</p><h1 style="font-size:40px;margin:8px 0">Switch and Latch Busy Board</h1><p>Light switches, a gate latch, a zip and a dial, screwed onto smooth wood. Made for ages 1 to 3, and for your twenty quiet minutes.</p>' +
    '<!-- BLOCO: preco --><p class="price" style="margin:16px 0">$69.95<s>$119.95</s></p><p style="font-size:13px;color:#6b6656;margin-bottom:12px">GST included · free shipping over $99</p>' +
    '<!-- BLOCO: order-bump --><div class="card" style="margin-bottom:14px"><label><input type="checkbox"> Add the Quiet Time Activity Cards (printable PDF) · <b>$9.95</b> <small>(30 ways to play with the board)</small></label></div>' +
    '<a class="btn" style="display:block;text-align:center" href="#">Add to cart</a>' +
    '<!-- BLOCO: bullets-objecao --><ul style="margin:18px 0 0 18px;line-height:1.9"><li><b>Will a part come off?</b> Every switch, latch and knob is screwed through the board, and we pull-test every batch.</li><li><b>Will they get bored?</b> Five activities in one board, plus 30 ideas in the printable cards.</li><li><b>Is it noisy?</b> No horn, no music. Small LEDs and the click of a switch.</li><li><b>Batteries?</b> 2 x AA behind a screw. No button batteries.</li></ul>' +
    '<!-- BLOCO: faixa-confianca --><p style="margin-top:16px;font-size:13px;color:#6b6656">Ships in 1 to 2 business days · Delivery in 6 to 12 business days · 30-day guarantee</p></div></div></section>' +
    '<!-- BLOCO: editorial-beat --><section class="sec" style="background:#fff"><div class="wrap hero" style="display:grid;grid-template-columns:1fr 1fr;gap:30px;align-items:center"><div class="ph" style="min-height:300px">IMAGEM 3 · prova_sossego: toddler focused on the board, mum cooking in the background</div><div><h2 style="font-size:30px">Five o\'clock, sorted.</h2><p style="margin-top:10px">They already love the light switch in the hallway. Give them a board full of switches that are theirs, and get dinner on the table.</p></div></div></section>' +
    '<!-- BLOCO: upsell --><section class="sec"><div class="wrap"><h2 style="font-size:28px;margin-bottom:16px">Make it a gift</h2><div class="grid"><div class="card"><div class="ph" style="min-height:160px">IMAGEM 5 · quiet time kit</div><p style="margin-top:8px">Quiet Time Kit · $99.95 <small>(save $24.90, ships free)</small></p></div><div class="card"><div class="ph" style="min-height:160px">IMAGEM 4 · travel busy book</div><p style="margin-top:8px">Travel Busy Book · $39.95</p></div></div></div></section>' +
    '<!-- BLOCO: faq --><section class="sec" style="background:#fff"><div class="wrap"><h2 style="font-size:28px;margin-bottom:12px">FAQ</h2><p><b>What age is it for?</b> 1 to 3 years, with supervision. Not for children under 12 months.</p><p style="margin-top:8px"><b>How big is it?</b> About the size of an A4 page, and light enough for a nappy bag.</p><p style="margin-top:8px"><b>How do I clean it?</b> Wipe with a damp cloth. Do not soak.</p></div></section>' +
    '<!-- BLOCO: sticky-mobile --><div class="sticky"><span class="price" style="font-size:18px">$69.95</span><a class="btn" href="#">Add to cart</a></div></body></html>';
}
