// Telas 00-04 (decidir + entender) da pesquisa Baby & Parenting > Montessori (AU).
import fs from 'node:fs';
import path from 'node:path';
import * as S from './shell.mjs';
import { LOJAS, ECON, manifesto, voz, demandaCont, radar, DADOS, CONV_PCT, CPA_PCT_V, MIN, MARCAS, FILTRADOS, MARCAS_F } from './dados-pesquisa.mjs';
const { esc, attr, n, usd, aud, pct, dmy, nat, na, pill, stat, note, table, td, tr, evidence, gates, btn, doc, pageHead, toc, sec, footer, legendNat, legendVer, dfn, adlib, VER_CLS } = S;

const cont = JSON.parse(fs.readFileSync(path.join(DADOS, 'mcp-contagens.json'), 'utf8')).consultas;
const get = (t, p, s) => (cont.find(c => c.termo === t && c.pais === p && c.status === s) || {}).total;
const PAISES = [['US', 'Estados Unidos'], ['CA', 'Canadá'], ['GB', 'Reino Unido'], ['AU', 'Austrália'], ['DE', 'Alemanha'], ['FR', 'França'], ['NL', 'Holanda'], ['ES', 'Espanha']];
const TRENDS = (t, geo = 'AU') => 'https://trends.google.com/trends/explore?date=today%205-y&geo=' + geo + '&hl=en&q=' + encodeURIComponent(t);
const ADLIB_T = t => 'https://www.facebook.com/ads/library/?active_status=active&ad_type=all&country=AU&q=' + encodeURIComponent(t) + '&search_type=keyword_unordered';
const AMZ = t => 'https://www.amazon.com.au/s?k=' + encodeURIComponent(t);
const TD = LOJAS.find(l => l.slug === 'toddla');
const MT = 'montessori toys';

/* ================= 00 CENTRAL ================= */
export function central() {
  const L = LOJAS;
  const body = pageHead({ eyebrow: S.CASE.code + ' · raio-x de nicho · nível iniciante · Austrália', h1: 'Baby &amp; Parenting: o <em>busy board</em> Montessori', answer: 'Vale a pena um iniciante entrar em Baby &amp; Parenting? Sim, por uma porta só: o painel de interruptores e trincos de madeira que segura a criança de 1 a 3 anos por 20 minutos sem tela, vendido na Austrália.', meta: ['coleta 06/10/2026', 'Meta Ads (conector oficial) + Biblioteca pública', 'IRP Commerce ago/2026 (Baby & Child)', '5 lojas dropship com ficha completa', 'SimilarWeb bloqueado: faturamento por proxy'] }) +
    toc([['decisao', 'Decisão'], ['portoes', 'Portões'], ['evidencia', 'Evidência'], ['numeros', 'Números'], ['ranking', 'Ranking'], ['economia', 'Economia'], ['limites', 'O que não foi medido'], ['proxima', 'Próxima ação']]) +
    sec('decisao', '00', 'Decisão',
      '<div class="decision"><div class="main-card">' +
      '<div class="scale5" role="img" aria-label="Escala de decisão: de Reprovado a Aprovado com nota máxima. Este nicho ficou em Aprovado"><span class="sc-item">Reprovado</span><span class="sc-item">Fraco</span><span class="sc-item">Observar</span><span class="sc-item is-on">Aprovado</span><span class="sc-item">Aprovado (nota máxima)</span></div>' +
      '<span class="badge">APROVADO: SIGA AS RECOMENDAÇÕES</span>' +
      '<p class="tese" style="margin-top:14px">Dá para vender brinquedo Montessori para pais e avós, e dá para começar pequeno. Quatro lojas que não fabricam nada (só revendem de fornecedor) vendem busy board, e em três delas ele é o produto principal: um painel de madeira com interruptores e trincos por uns 40 a 50 dólares. Uma delas é australiana, a toddla.co, com 1.059 anúncios no ar e o anúncio do painel rodando há 99 dias, o que quer dizer que ele se paga.</p>' +
      '<ol class="recs">' +
      '<li><b>Comece só pelo busy board de interruptores.</b> É o campeão de 3 das 4 lojas modelo (a quarta também vende), e um produto só é mais fácil de testar.</li>' +
      '<li><b>Venda na Austrália, não nos EUA.</b> Nos EUA, todo pacote da China paga tarifa (de 17,5% a 35%) e o brinquedo precisa de certificado enviado à alfândega. Na Austrália não há tarifa nesse valor e o processo é mais simples.</li>' +
      '<li><b>Só compre de fornecedor que mande o laudo de segurança do brinquedo.</b> Em 2026 houve recall de 276 mil busy boards na Amazon porque um botão soltava e a criança podia engasgar. Peça a amostra e puxe cada peça com força antes de anunciar.</li>' +
      '<li><b>Venda o sossego, não a "educação".</b> Os anúncios que duram meses falam do café que ficou quente e do jantar que deu para fazer. Use o PDF de atividades (A$ 9,95) e o livro de viagem como itens extras: são eles que folgam a conta.</li>' +
      '</ol>' +
      '<p class="why"><b>Se pular as recomendações:</b> o risco maior não é perder dinheiro, é vender um brinquedo com peça que solta. Sem o laudo e o teste de puxar, não anuncie.</p>' +
      '<div class="btns">' + btn('Ver o plano de ação', 'paginas/plano-de-acao.html', 'primary') + btn('Abrir a estratégia', 'paginas/estrategia.html') + btn('Ver limites da análise', 'paginas/metodo.html', 'ghost') + '</div>' +
      '</div><div class="q3">' +
      '<div class="q"><span class="eyebrow">1 · Qual oportunidade</span><p><b>Wattlebee Switch and Latch Busy Board</b>, ' + dfn('busy board') + ' de madeira com interruptores, A$ 69,95 (de A$ 119,95), com cartões de atividade em PDF de A$ 9,95 como ' + dfn('order bump') + ', ' + dfn('busy book') + ' de viagem de A$ 39,95 como ' + dfn('upsell') + ' e kit de presente de A$ 99,95. Austrália, inglês, AUD.</p></div>' +
      '<div class="q"><span class="eyebrow b">2 · O que os dados sustentam</span><p>4 lojas ' + dfn('dropshipping') + ' de busy board com 119 a 3.100 anúncios ativos, anúncios do painel no ar há 99 a 120 dias. Não sustentam: visitas e faturamento exatos (o SimilarWeb bloqueou), custo real do fornecedor, gasto em mídia.</p></div>' +
      '<div class="q"><span class="eyebrow g">3 · Próxima ação</span><p>Pedir amostra do busy board de interruptores a 2 fornecedores que mandem o laudo de segurança, e fazer o teste de puxar cada peça.</p></div>' +
      '</div></div>') +
    sec('portoes', '01', 'Os sete portões', gates('gd-central', [
      { st: 'pass', k: 'obs', o: n(get(MT, 'US', 'ACTIVE'), 0) + ' anúncios ativos de "montessori toys" nos EUA e ' + n(get(MT, 'AU', 'ACTIVE'), 0) + ' na Austrália; toddla.co (1.059), Tibatoes (3.100), Lovealotter (261) e Montessori Paradise (119) vendem busy board.', src: 'Conector Meta Ads, 06/10/2026. Contagem por palavra-chave tem ruído (ver Mercados).' },
      { st: 'pass', k: 'obs', o: 'Do busy board saem busy book, árvore de feltro, PDF de atividades e kits; as lojas vendem bundles de US$ 49,99 a US$ 149,99.', src: 'Catálogo (products.json) das lojas, 06/10/2026.' },
      { st: 'pass', k: 'obs', o: 'Ângulos variam (sem tela, sossego, interruptor liberado, presente de avó, viagem de carro) e o nicho roda em vídeo (66% dos ' + n(FILTRADOS, 0) + ' anúncios do nicho).', src: n(MIN, 0) + ' anúncios extraídos da Biblioteca pública, ' + n(FILTRADOS, 0) + ' depois de tirar o ruído.' },
      { st: 'warn', k: 'calc', o: 'Com A$ 69,95 + A$ 9,95 de frete e custo por venda conservador de A$ 35, sobram ' + aud(ECON.margemCoreCons) + ' só com o board; com PDF e busy book no pedido, ' + aud(ECON.margemEscCons) + '.', src: 'Custo de fornecedor é estimativa (sem amostra). CPA de A$ 35 é premissa conservadora, não medição.' },
      { st: 'pass', k: 'inf', o: 'Lojas de 2026 entrando agora (Montessori Paradise, aberta em 01/2026, já com 119 anúncios) e a toddla.co subindo no ranking de tráfego (Tranco). O nicho ainda aceita quem chega, com pico em novembro e dezembro.', src: 'Datas de catálogo + contagem por page_id + Tranco.' },
      { st: 'warn', k: 'inf', o: 'Sem vantagem própria ainda: a brecha é provar a segurança em imagem (a peça que não sai, a pilha parafusada), que nenhum concorrente mostra.', src: 'Auditoria de carrossel de 6 páginas de produto concorrentes.' },
      { st: 'warn', k: 'inf', o: 'Produto leve e simples, mas é brinquedo para menor de 3 anos: exige fornecedor com laudo de segurança e teste de amostra. É o passo que o iniciante não pode pular.', src: 'Recall Esjay (276 mil unidades, 2026); padrão australiano para brinquedos até 36 meses.' },
    ]) + '<p class="lead" style="margin-top:12px">Clique em cada portão para ver o que foi observado e o limite.</p>') +
    sec('evidencia', '02', 'Linha de evidência', evidence({ fonte: 'Meta Ads (contagem por página e termo), Biblioteca pública (' + n(MIN, 0) + ' anúncios), products.json, reviews, prints.', obs: 'toddla.co 1.059 ativos/3.392, Tibatoes 3.100/11.300, Lovealotter 261/275, Montessori Paradise 119/338; anúncio do busy board da toddla.co no ar há ~99 dias e o da Lovealotter há ~120.', interp: 'Existe compra recorrente de busy board de US$ 40 a 50 por pais que querem 20 minutos de sossego sem tela, e por avós no Natal. O que trava o comprador é segurança ("e se soltar uma peça?") e "vai enjoar em 2 minutos".', dec: 'APROVADO: entrar na Austrália com 1 produto e a escada board + PDF + busy book, puxando para o kit de presente.', next: 'Amostra de 2 fornecedores com laudo; teste de puxar cada peça.' }) + legendNat()) +
    sec('numeros', '03', 'Os números que sustentam', '<div class="grid g4">' +
      stat({ v: '119 a 3.100', l: 'anúncios ativos por loja de busy board', d: 'toddla.co, Tibatoes, Lovealotter, Montessori Paradise', k: 'obs', src: 'Meta Ads, page_id' }) +
      stat({ v: '~120 dias', l: 'anúncio do busy board ainda no ar (Lovealotter)', d: 'acima de 60 dias, já se pagou', k: 'obs', src: 'Biblioteca pública' }) +
      stat({ v: n(get(MT, 'AU', 'ACTIVE'), 0), l: 'anúncios "montessori toys" ativos na Austrália', d: 'proporcionalmente o mercado mais denso dos 8 países', k: 'obs', src: 'Meta Ads, 06/10/2026' }) +
      stat({ v: aud(ECON.aov), l: 'ticket médio projetado com a escada', d: 'board + PDF (30%) + busy book (12%) + frete', k: 'calc' }) + '</div>' + note('<b>Ciclo de vida do nicho: ESCALANDO.</b> Lojas de 2025 e 2026 com centenas de anúncios ativos, uma australiana (toddla.co) crescendo no Tranco e campanhas de Natal começando agora. <b>Benchmark de custo:</b> setor Baby &amp; Child do IRP (ago/2026, lojas do Reino Unido): ' + dfn('CPA') + ' 10,92% da receita, conversão 0,57% e ticket médio de £855,57, distorcido por carrinho e berço: usado só como piso. ' + dfn('CPM') + ' e ' + dfn('CPC') + ': referência pública da Meta para e-commerce em 2026, US$ 10,42 e US$ 0,67.', 'b', 'momentum e benchmark')) +
    sec('ranking', '04', 'Ranking das lojas', legendVer() + table(['#', 'Loja', 'Linha', { t: 'Ativos', num: true }, { t: 'Histórico', num: true }, 'Visitas/mês', { t: 'Ticket', num: true }, 'Modelo', 'Veredito'],
      L.map((l, i) => tr([td(i + 1, 'num'), td('<a href="paginas/loja-' + l.slug + '.html">' + esc(l.nome) + '</a>'), td(l.lado), td(n(l.ativos, 0), 'num'), td(n(l.historico, 0), 'num'), td(na('SimilarWeb bloqueou')), td(usd(l.ticket, 2), 'num'), td(esc(l.modelo)), td(pill(l.veredito, VER_CLS[l.veredito]))]))) +
      note('Fora do ranking por não serem replicáveis por iniciante (estoque próprio, armazém, marca registrada ou produção artesanal): Montessori Generation (779 anúncios ativos, armazéns nos EUA, Austrália, Europa e Ásia, 5 anos de operação, marca registrada nos EUA), Joyreal (armazéns próprios nos EUA, Reino Unido e Espanha), TinyBusy (livro artesanal com armazém no Texas). Aparecem só como contexto.', 'a', 'leitura')) +
    sec('economia', '05', 'Economia por venda', '<div class="grid g4">' +
      stat({ v: aud(ECON.core), l: 'preço do busy board', d: '+ A$ 9,95 de frete abaixo de A$ 99', k: 'rec' }) +
      stat({ v: aud(ECON.custo + ECON.frete), l: 'produto + frete (estimativa)', d: 'sem amostra ainda', k: 'inf' }) +
      stat({ v: aud(ECON.cpaEquilibrioCore), l: dfn('CPA') + ' de equilíbrio', d: 'acima disso, a venda dá prejuízo', k: 'calc' }) +
      stat({ v: aud(ECON.margemEscCons), l: 'sobra por pedido com a escada', d: 'CPA de A$ 35 (conservador)', k: 'calc' }) + '</div>' +
      table(['Cenário', { t: 'Receita', num: true }, { t: 'Produto + frete', num: true }, { t: 'Taxa (3%)', num: true }, { t: 'CPA', num: true }, { t: 'Sobra', num: true }], [
        tr([td('Só o board (A$ 69,95 + A$ 9,95 de frete), CPA A$ 35'), td(aud(ECON.receitaCore), 'num'), td(aud(ECON.custo + ECON.frete), 'num'), td(aud(ECON.taxa), 'num'), td(aud(ECON.cpaCons), 'num'), td(aud(ECON.margemCoreCons), 'num')]),
        tr([td('Escada (board + PDF 30% + busy book 12%), CPA A$ 35'), td(aud(ECON.aov), 'num'), td('incluído', 'num'), td('incluída', 'num'), td(aud(ECON.cpaCons), 'num'), td(aud(ECON.margemEscCons), 'num')]),
        tr([td('Kit de presente (A$ 99,95, frete grátis), CPA A$ 35'), td(aud(ECON.kit), 'num'), td(aud(ECON.kitCusto), 'num'), td(aud(ECON.kit * ECON.taxaPct), 'num'), td(aud(ECON.cpaCons), 'num'), td(aud(ECON.margemKitCons), 'num')]),
      ]) + note('Em resumo: o board sozinho já paga o anúncio frio com sobra de ~A$ 14. O PDF (custo zero) e o busy book aumentam a sobra. O kit de presente rende menos por pedido, porque dá frete grátis e desconto, mas é ele que a avó compra no Natal: use como oferta de dezembro, não como produto principal. Preços com ' + dfn('GST') + ' incluído; abaixo de A$ 75 mil/ano em vendas não há GST a recolher.', 'b', 'em resumo')) +
    sec('limites', '06', 'O que não foi medido', table(['Dado', 'Situação', 'O que foi feito no lugar'], [
      tr([td('Visitas e faturamento das lojas'), td(na('SimilarWeb bloqueou a coleta automática (CloudFront); você preferiu seguir sem a extensão')), td('faturamento só da Montessori Paradise, por proxy de reviews verificados, marcado "estimado incerto"; nas outras, escala lida por anúncios')]),
      tr([td('Custo real do fornecedor'), td(na('sem amostra, sem cotação fechada')), td('faixa US$ 8 a 14 pelo busy board (trecho de busca do AliExpress); marcada como estimativa')]),
      tr([td('Gasto real dos concorrentes em anúncio'), td(na('a Meta não publica gasto para e-commerce fora da UE')), td('só para a Paradise: faturamento estimado x 10,92% (IRP)')]),
      tr([td('Benchmark do setor na Austrália'), td(na('o IRP publica dados de lojas do Reino Unido')), td('Baby & Child do IRP usado como ordem de grandeza, declarado')]),
      tr([td('Comentários dos anúncios'), td(na('o conector não devolve comentários')), td('objeções tiradas de reviews e guias públicos (voz do mercado)')]),
    ])) +
    sec('proxima', '07', 'Próxima ação', '<ol class="steps"><li><b>Dias 1 a 4.</b> Pedir amostra do busy board de interruptores (pilha AA com tampa parafusada) a 2 fornecedores que mandem o laudo de segurança de brinquedo; registrar custo e prazo para a Austrália.</li><li><b>Dias 5 a 9.</b> Teste da amostra: puxar com força cada interruptor, trinco e botão; abrir a tampa da pilha sem chave de fenda (não pode abrir); deixar uma criança de 1 a 3 anos brincar 20 minutos, com supervisão.</li><li><b>Dias 7 a 12.</b> Montar a loja Wattlebee com 6 itens (blueprint pronto na tela 08).</li><li><b>Dias 12 a 16.</b> Filmar a amostra (a criança concentrada + o teste de puxar), gerar as imagens com os prompts da tela 09 e subir 3 anúncios de teste a A$ 20/dia.</li></ol>' + btn('Abrir o plano de ação completo', 'paginas/plano-de-acao.html', 'primary')) +
    footer(true);
  return doc({ title: 'Central da oportunidade · Montessori', current: 'central', screen: { code: '00', title: 'Central da oportunidade' }, body, fromRoot: true, next: { t: 'Pedir amostra do busy board a 2 fornecedores com laudo', s: 'antes de qualquer foto ou anúncio', b: 'Ver o plano', h: 'paginas/plano-de-acao.html' } });
}

/* ================= 01 DEMANDA ================= */
const DC = (demandaCont && demandaCont.termos) || {};
const TERMOS = [
  ['busy board', 'comprar', 'produto-herói; base da loja', 'perene, pico em novembro e dezembro'],
  ['busy board for toddlers', 'comprar', 'produto-herói por idade', 'perene'],
  ['busy board for 1 year old', 'ocasião', 'presente de 1º aniversário', 'perene'],
  ['best montessori busy board', 'pesquisar', 'comparação antes de comprar (página "por que o nosso")', 'pico no Natal'],
  ['montessori busy board australia', 'comprar', 'o termo exato do mercado-alvo', 'perene'],
  ['light switch busy board', 'comprar', 'o mecanismo do seu produto (interruptor)', 'perene'],
  ['montessori toys australia', 'comprar', 'categoria no país-alvo', 'pico no Natal'],
  ['montessori toys for 1 year old', 'ocasião', 'idade do comprador principal', 'perene'],
  ['montessori toys for 2 year old', 'ocasião', 'segunda faixa de idade', 'perene'],
  ['montessori toys for babies', 'comprar', 'fase 2 (bebê de 6 a 12 meses)', 'perene'],
  ['toddler christmas gift', 'ocasião', 'kit de presente e árvore de feltro', 'novembro e dezembro'],
  ['busy book toddler', 'comprar', 'upsell (busy book de viagem)', 'pico antes das férias'],
  ['quiet book for toddlers', 'comprar', 'sinônimo de busy book', 'perene'],
  ['screen free toys for toddlers', 'problema', 'ângulo de anúncio "sem tela"', 'perene'],
  ['sensory board toddler', 'pesquisar', 'sinônimo do produto', 'perene'],
  ['educational toys for 1 year old', 'ocasião', 'presente de aniversário', 'perene'],
  ['travel toys for toddlers', 'ocasião', 'ângulo de viagem (busy book + sacola)', 'dezembro e janeiro (férias de verão na AU)'],
  ['personalised busy board', 'comprar', 'fase 2 (nome gravado)', 'pico no Natal'],
];
const cel = t => DC[t] ? n(DC[t].total, 0) + ' ' + nat('obs') + (DC[t].ruido && !DC[t].ruido.startsWith('baixo') ? '<br><small>ruído ' + esc(DC[t].ruido.split(':')[0]) + '</small>' : '') : '<small>contagem não levantada nesta rodada</small>';
const CAND = (demandaCont && demandaCont.candidatos_sem_contagem) || [];

export function demanda() {
  const linhas = TERMOS.map(([t, int, uso, saz]) => tr([td('<b>' + esc(t) + '</b>'), td(cel(t), 'num'), td(int), td(uso), td(saz), td('<a href="' + TRENDS(t) + '" target="_blank" rel="noopener">Trends ↗</a> · <a href="' + ADLIB_T(t) + '" target="_blank" rel="noopener">Anúncios ↗</a> · <a href="' + AMZ(t) + '" target="_blank" rel="noopener">Amazon ↗</a>')]));
  const cand = CAND.map(t => tr([td('<b>' + esc(t) + '</b>'), td('<small>contagem não levantada nesta rodada</small>'), td('<a href="' + TRENDS(t) + '" target="_blank" rel="noopener">Trends ↗</a> · <a href="' + ADLIB_T(t) + '" target="_blank" rel="noopener">Anúncios ↗</a>')]));
  const top5 = 'https://trends.google.com/trends/explore?date=today%205-y&geo=AU&hl=en&q=' + ['busy board', 'montessori toys', 'busy book', 'quiet book', 'sensory board'].map(encodeURIComponent).join(',');
  const body = pageHead({ eyebrow: '01 · evidências · demanda observada · Austrália', h1: 'As pessoas <em>procuram</em> e compram isso?', answer: 'Sim. "busy board" e "montessori toys" aparecem em 1º lugar no autocomplete do Google e do Bing na Austrália, há anúncio de busy board no ar há mais de 100 dias, e o comprador fala sempre das mesmas duas coisas: "preciso de 20 minutos sem tela" e "e se soltar uma peça?".', meta: ['autocomplete Google (gl=au) + Bing (en-AU): 527 termos', 'Meta Ads, 18 termos contados na AU', 'links prontos para Google Trends'] }) +
    toc([['sinal', 'Sinal mais forte'], ['termos', 'Palavras e links'], ['candidatos', 'Termos sem contagem'], ['motivos', 'Por que compram'], ['meta', 'Anúncios por país'], ['midia', 'Mídia por loja'], ['voz', 'Voz do mercado'], ['decisao', 'Decisão']]) +
    sec('sinal', '01', 'O sinal mais forte', '<div class="grid g4">' +
      stat({ v: '~120 dias', l: 'anúncio do busy board de interruptores no ar', d: 'Lovealotter: "Finally, A Toy They\'re Allowed To Touch"', k: 'obs', src: 'Biblioteca pública' }) +
      stat({ v: '1º', l: 'posição de "busy board australia" e "montessori toys australia" no autocomplete', d: 'Google e Bing ao mesmo tempo', k: 'obs', src: 'autocomplete público, 06/10/2026' }) +
      stat({ v: n(get(MT, 'AU', 'ACTIVE'), 0), l: 'anúncios "montessori toys" ativos na AU', d: n(get(MT, 'US', 'ACTIVE'), 0) + ' nos EUA, com 13x a população', k: 'obs', src: 'Meta Ads, 06/10/2026' }) +
      stat({ v: '+47,4%', l: 'crescimento de vendas do setor Baby & Child', d: 'ago/2026 contra ago/2025 (IRP, Reino Unido)', k: 'obs', src: 'IRP Commerce' }) + '</div>' +
      note('Contagem por palavra-chave mede quanta gente anuncia aquilo, não quanta gente procura. A curva de busca de 5 anos você vê clicando nos links do Google Trends abaixo (já filtrados na Austrália). Volume mensal exato de busca não foi medido: esta pesquisa não usa ferramenta paga de palavra-chave.', 'b', 'como ler')) +
    sec('termos', '02', 'Palavras que o comprador usa (com link pronto)', '<p class="lead">Clique e veja o gráfico de 5 anos no Google Trends já filtrado na Austrália, os anúncios ativos na ' + dfn('Biblioteca de Anúncios') + ' e o que vende na Amazon Austrália. ' + btn('Comparar os 5 principais no Trends', top5, 'sm', true) + '</p>' +
      table(['Termo', { t: 'Anúncios ativos (AU)', num: true }, 'Intenção', 'Para que serve no plano', 'Sazonalidade provável', 'Links'], linhas) +
      note('A Biblioteca busca palavras soltas, não a frase: "busy board" trouxe romance (casa "busy" e "board" separados) e "quiet book" trouxe livro de ficção. Por isso o número vem com o nível de ruído ao lado. Use os de ruído baixo como sinal ("light switch busy board" 41, "montessori toys for babies" 40, "best montessori busy board" 59) e os outros só como ordem de grandeza.', 'a', 'limite')) +
    sec('candidatos', '03', 'Termos fortes sem contagem nesta rodada', '<p class="lead">Vieram no topo do autocomplete, mas a contagem de anúncios não foi levantada. Abra o link e veja você mesmo.</p>' + table(['Termo', 'Anúncios', 'Links'], cand)) +
    sec('motivos', '04', 'Por que as pessoas compram (e por que desistem)', '<div class="grid g2">' +
      '<div class="card"><span class="eyebrow g">Por que compra</span><p>Os 20 minutos de sossego sem culpa de tela: cozinhar, trabalhar, tomar o café quente. É o que dizem os títulos que mais duram ("Five minutes, coffee still hot", "5pm isn\'t a crisis anymore").</p></div>' +
      '<div class="card"><span class="eyebrow r">Por que frustra</span><p>Peça que solta (recall de 276 mil busy boards da Esjay na Amazon), buzina e pilha que irritam ("the horn button can be an annoyance"), e "enjoou em 2 minutos".</p></div>' +
      '<div class="card"><span class="eyebrow b">Retenção</span><p>Quem gostou do board compra o busy book de viagem e a árvore de feltro no Natal: as 4 lojas modelo vendem bundle.</p></div>' +
      '<div class="card"><span class="eyebrow a">Segundo comprador</span><p>A avó. Montessori Paradise e Montessori Generation anunciam lista de presentes "que a avó não se arrepende" em outubro: é o mesmo produto para outra pessoa.</p></div></div>') +
    sec('meta', '05', 'Anúncios por termo e país', table(['País', { t: 'montessori toys', num: true }, { t: 'montessori busy board', num: true }, { t: 'montessori toddler', num: true }], PAISES.map(([c, nm]) => tr([td(nm), td(n(get(MT, c, 'ACTIVE'), 0), 'num'), td(n(get('montessori busy board', c, 'ACTIVE'), 0), 'num'), td(n(get('montessori toddler', c, 'ACTIVE'), 0), 'num')]))) + note('A tabela completa, com inativos e a leitura de cemitério, está em ' + btn('Mercados e país', 'mercados.html', 'sm') + '.', 'b')) +
    sec('midia', '06', 'Mídia por loja', '<div class="grid g4">' + LOJAS.slice(0, 4).map(l => stat({ v: n(l.ativos, 0), l: 'anúncios ativos ' + esc(l.nome), d: (l.sobrev != null ? pct(l.sobrev) + ' do histórico no ar' : ''), k: 'obs', src: 'Meta Ads, page_id' })).join('') + '</div>' +
      table(['Camada', 'O que confirma', 'O que não permite concluir'], [tr([td('Anúncios ativos e longevos'), td('alguém paga para manter aquele anúncio no ar'), td('quanto vende nem quanto lucra')]), tr([td('Autocomplete do Google e Bing'), td('as pessoas digitam aquilo'), td('quantas vezes por mês')]), tr([td('Voz do mercado'), td('as palavras e os medos do comprador'), td('quantas pessoas pensam assim')]), tr([td('Visitas (SimilarWeb)'), td(na('bloqueado nesta coleta')), td('-')])])) +
    sec('voz', '07', 'Voz do mercado', '<div class="grid g2">' + (voz ? voz.dores_objecoes.map(d => '<div class="card"><span class="eyebrow a">dor ou objeção</span><p>"' + esc(d.frase) + '"</p><p><small>' + esc(d.contexto) + ' · fonte: ' + esc(d.fonte) + '</small></p></div>').join('') : '') + '</div>' +
      note('Provas que o comprador procura: ' + (voz ? voz.provas_que_o_comprador_quer.map(esc).join('; ') : '') + '.', 'g', 'o que responde a objeção')) +
    sec('decisao', '08', 'Decisão de demanda', evidence({ fonte: 'Meta Ads, Biblioteca pública, autocomplete Google e Bing, reviews e guias públicos.', obs: 'Busy board em 1º no autocomplete australiano; anúncio de busy board no ar há ~120 dias; 4 lojas de busy board com 119 a 3.100 ativos.', interp: 'Demanda real e perene, ligada a uma dor diária (o pai precisa de 20 minutos), com pico de presente no Natal. O medo de "soltar peça" é o que decide a compra.', dec: 'Demanda aprovada para o busy board de interruptores.', next: 'Abrir os links do Trends para ver o pico de dezembro e lançar antes de novembro.' }) +
      '<div class="btns" style="margin-top:12px">' + btn('Ver os criativos', 'anuncios.html') + btn('Abrir o plano', 'plano-de-acao.html', 'primary') + '</div>') +
    footer(false);
  return doc({ title: 'Demanda observada · Montessori', current: 'demanda', screen: { code: '01', title: 'Demanda observada' }, body, next: { t: 'Ver a curva de 5 anos no Google Trends (Austrália)', b: 'Abrir Trends', h: top5, ext: true } });
}

/* ================= 02 MERCADOS ================= */
export function mercados() {
  const linhas = PAISES.map(([c, nm]) => {
    const a = get(MT, c, 'ACTIVE'), bb = get('montessori busy board', c, 'ACTIVE'), tdd = get('montessori toddler', c, 'ACTIVE');
    const aT = a + get(MT, c, 'INACTIVE');
    const raz = bb / a;
    return tr([td('<b>' + nm + '</b>'), td(n(a, 0) + ' <small>(' + pct(a / aT * 100) + ' no ar)</small>', 'num'), td(n(bb, 0), 'num'), td(n(tdd, 0), 'num'), td(n(raz, 2), 'num'), td(c === 'AU' ? pill('alvo', 'g') : c === 'US' ? pill('maior, mas com tarifa e certificado', 'a') : ['CA', 'GB'].includes(c) ? pill('fase 2', 'b') : pill('idioma: medir em nativo', 'a'))]);
  });
  const carr = radar && radar.matriz_radar ? radar.matriz_radar.carregador_bebe : null;
  const body = pageHead({ eyebrow: '02 · evidências · mercados · matriz de 8 países', h1: 'Em que <em>país</em> começar?', answer: 'Austrália. Os EUA têm o maior volume (' + n(get(MT, 'US', 'ACTIVE'), 0) + ' anúncios ativos de "montessori toys"), mas lá todo pacote da China paga tarifa e o brinquedo precisa de certificado enviado à alfândega. A Austrália tem ' + n(get(MT, 'AU', 'ACTIVE'), 0) + ' anúncios ativos com 1/13 da população, a maior proporção no ar da matriz, e uma loja local (toddla.co) crescendo.', meta: ['48 consultas no conector Meta Ads', '3 termos x 8 países x ativo/inativo', 'radar de 3 sub-nichos antes da escolha', '06/10/2026'] }) +
    toc([['radar', 'Como o sub-nicho foi escolhido'], ['metodo', 'Método'], ['tabela', 'Tabela de países'], ['regras', 'Regras por país'], ['sequencia', 'Sequência de entrada']]) +
    sec('radar', '01', 'Como o sub-nicho foi escolhido', '<p class="lead">"Baby &amp; Parenting" é uma categoria, não um nicho. O radar mediu 9 sementes nos EUA e 3 candidatos nos 8 países.</p>' +
      table(['Sub-nicho', { t: 'EUA', num: true }, { t: 'AU', num: true }, { t: 'CA', num: true }, { t: 'UK', num: true }, 'Resultado'], [
        tr([td('Carregador de bebê ("baby carrier")'), td(n(carr ? carr.US : 3749, 0), 'num'), td(n(carr ? carr.AU : 1490, 0), 'num'), td(n(carr ? carr.CA : 1302, 0), 'num'), td(n(carr ? carr.GB : 1216, 0), 'num'), td(pill('descartado', 'r') + ' produto regulado (ASTM F2236 + certificado CPC nos EUA), com recall de 18.650 slings da Temu e alerta da CPSC por risco de queda')]),
        tr([td('<b>Brinquedos Montessori</b>'), td(n(get(MT, 'US', 'ACTIVE'), 0), 'num'), td(n(get(MT, 'AU', 'ACTIVE'), 0), 'num'), td(n(get(MT, 'CA', 'ACTIVE'), 0), 'num'), td(n(get(MT, 'GB', 'ACTIVE'), 0), 'num'), td(pill('escolhido', 'g') + ' lojistas reais no topo, presente de avó, risco menor e fornecedor com laudo mais fácil de achar')]),
        tr([td('Alimentação em silicone'), td('243', 'num'), td('ruído', 'num'), td('ruído', 'num'), td('ruído', 'num'), td(pill('descartado', 'r') + ' mercado estreito e ticket baixo (US$ 20 a 40)')]),
      ]) + note('Também testados nos EUA e descartados por ruído (romance, drama, app): "baby sleep sack", "white noise machine baby", "teething toys", "stroller organizer". Dados em ' + btn('radar-subnichos.json', '../dados/radar-subnichos.json', 'sm') + ' e ' + btn('matriz do carregador', '../dados/descartado-carregador/matriz-paises.json', 'sm') + '.', 'b')) +
    sec('metodo', '02', 'Como foi medido', '<div class="grid g2"><div class="card"><span class="eyebrow b">termo amplo</span><p><b>"montessori toys"</b> mede quanto dinheiro anda em anúncio de brinquedo Montessori no país. É um termo limpo: no topo da amostra aparecem lojas de brinquedo, não romance.</p></div><div class="card"><span class="eyebrow b">termos de ângulo</span><p><b>"montessori busy board"</b> (o produto) e <b>"montessori toddler"</b> (a idade). Sem a palavra "montessori", "busy board" e "toddler learning toys" vieram cheios de ruído e foram trocados.</p></div></div>') +
    sec('tabela', '03', 'Tabela de países', table(['País', { t: 'montessori toys (ativos)', num: true }, { t: 'montessori busy board', num: true }, { t: 'montessori toddler', num: true }, { t: 'Razão busy board ÷ amplo', num: true }, 'Leitura'], linhas) +
      note('A Biblioteca casa palavras soltas: por isso os termos de ângulo voltam MAIORES que o termo amplo (razão acima de 1), e a razão aqui não mede espaço livre, só ordem de grandeza. Os INATIVOS também vêm inflados por ruído antigo, e por isso o arquivo técnico marca quase todos os territórios como "cemitério". Use os ATIVOS como sinal principal. Em alemão, francês, holandês e espanhol, os termos locais ("Montessori Spielzeug", "jouet montessori") deram de 33 a 78 ativos no radar.', 'a', 'limite') + legendNat() +
      '<div class="btns" style="margin-top:10px">' + btn('Arquivo da matriz (JSON)', '../dados/matriz-paises.json', 'sm') + btn('Contagens brutas (JSON)', '../dados/mcp-contagens.json', 'sm') + '</div>') +
    sec('regras', '04', 'O que muda entre EUA e Austrália', table(['Ponto', 'Estados Unidos', 'Austrália'], [
      tr([td('Imposto de importação do pacote'), td('sem isenção desde 2025: brinquedo da China paga de 17,5% a 35% (as fontes divergem)'), td('sem tarifa abaixo de A$ 1.000; o ' + dfn('GST') + ' de 10% vai embutido no preço')]),
      tr([td('Certificado do brinquedo'), td(dfn('CPC (certificado)') + ' emitido pelo importador, laudo de laboratório credenciado, e envio eletrônico à alfândega desde 08/07/2026'), td('padrão obrigatório para brinquedo de criança até 36 meses (peças pequenas); o vendedor responde por ele, sem envio à alfândega')]),
      tr([td('Tamanho do mercado no Meta'), td(n(get(MT, 'US', 'ACTIVE'), 0) + ' anúncios ativos'), td(n(get(MT, 'AU', 'ACTIVE'), 0) + ' anúncios ativos, com 1/13 da população')]),
      tr([td('Loja local que já vende'), td('várias (Tibatoes, Montessori Paradise, Lovealotter vendem em USD)'), td('toddla.co (australiana, crescendo)')]),
    ]) + note('Fontes: CPSC (16 CFR 1250 / ASTM F963), alfândega dos EUA (fim do de minimis), ACCC (padrão de brinquedo até 36 meses). Isso não é aconselhamento jurídico: confirme com o fornecedor e, se escalar, com um despachante.', 'b')) +
    sec('sequencia', '05', 'Sequência de entrada', '<ol class="steps"><li><b>Austrália, inglês, AUD.</b> Começar aqui: mercado denso, sem tarifa e com uma loja local provando o modelo.</li><li><b>Nova Zelândia</b> com a mesma loja e o mesmo inglês, quando o board passar de 20 vendas por semana.</li><li><b>Reino Unido e Canadá</b> só depois de ajustar preço, prazo e o padrão de brinquedo de cada país (UKCA no Reino Unido).</li><li><b>Estados Unidos</b> só com fornecedor que entregue o CPC e com a tarifa embutida no preço.</li><li><b>Alemanha, França, Holanda, Espanha:</b> medir de novo com termos no idioma nativo antes de decidir.</li></ol>' +
      evidence({ fonte: 'Conector Meta Ads, 48 consultas + radar de 3 sub-nichos.', obs: 'EUA lideram em volume; a Austrália tem a maior proporção de "montessori toys" no ar (' + pct(get(MT, 'AU', 'ACTIVE') / (get(MT, 'AU', 'ACTIVE') + get(MT, 'AU', 'INACTIVE')) * 100) + ').', interp: 'Mercado proporcionalmente denso e mais simples de operar para iniciante.', dec: 'País da loja: Austrália.', next: 'Configurar a loja em inglês, AUD, frete para a Austrália.' })) +
    footer(false);
  return doc({ title: 'Mercados e país · Montessori', current: 'mercados', screen: { code: '02', title: 'Mercados e país' }, body, next: { t: 'Ver as lojas que já vendem busy board', b: 'Concorrentes', h: 'concorrentes.html' } });
}

/* ================= 03 CONCORRENTES ================= */
export function concorrentes() {
  const cards = LOJAS.map(l => '<a class="card link" href="loja-' + l.slug + '.html"><span class="eyebrow ' + VER_CLS[l.veredito] + '">' + esc(l.lado) + ' · ' + esc(l.modelo) + '</span><h3>' + esc(l.nome) + '</h3><p>' + n(l.ativos, 0) + ' anúncios ativos · ticket ' + usd(l.ticket, 2) + ' · campeão ' + esc(l.campeao.titulo) + '</p><p>' + pill(l.veredito, VER_CLS[l.veredito]) + ' ' + pill('nível ' + l.nivel, 'b') + ' ' + pill(l.defens, l.defens === 'CONSTRUÍVEL' ? 'g' : 'a') + '</p><p><small>' + esc(l.momento) + '</small></p></a>').join('');
  const fat = LOJAS.map(l => tr([td('<a href="loja-' + l.slug + '.html">' + esc(l.nome) + '</a>'), td(l.fat ? usd(l.fat) : na('sem visitas nem reviews verificáveis'), 'num'), td(l.fat ? usd(l.fatMin) + ' a ' + usd(l.fatMax) : '-', 'num'), td(l.midiaMes ? usd(l.midiaMes) : '-', 'num'), td(l.fat ? 'reviews verificados ÷ taxa de review x ticket ' + nat('inf') + ' · estimado incerto' : 'não estimado (sem base medida)')]));
  const aud2 = LOJAS.map(l => '<div class="card"><span class="eyebrow g">' + esc(l.nome) + '</span><div class="vs"><b>' + n(l.ativos, 0) + ' ativos</b><s>' + n(l.historico, 0) + ' no histórico</s></div><p><small>page_id ' + l.pageIds.join(', ') + '</small></p></div>').join('');
  const body = pageHead({ eyebrow: '03 · evidências · 5 operações dropship · veredito por loja', h1: 'Quem já <em>vende</em> isso e dá para copiar?', answer: 'Quatro lojas servem de modelo, três delas com o busy board como campeão: toddla.co (a australiana, com cara de marca), Tibatoes (a que mais anuncia), Lovealotter (a mais simples) e Montessori Paradise (a do presente para avó, cujo campeão é a Discovery Box, mas que também vende busy board). A Clever Toys Box vende pouco volume: fica para observar.', meta: ['contagem por page_id achado pelo domínio', '15 prints (home, produto, carrinho)', 'reviews e catálogo por loja'] }) +
    toc([['lojas', 'As 5 lojas'], ['faturamento', 'Faturamento estimado'], ['auditoria', 'Auditoria de contagem'], ['leitura', 'Leitura']]) +
    sec('lojas', '01', 'As 5 lojas', legendVer() + '<div class="grid g2">' + cards + '</div>') +
    sec('faturamento', '02', 'Faturamento estimado por loja', table(['Loja', { t: 'Receita/mês (central)', num: true }, { t: 'Faixa', num: true }, { t: 'Mídia/mês estimada', num: true }, 'Método'], fat) +
      note('O SimilarWeb bloqueou a coleta automática e você escolheu seguir sem a extensão. Por isso só a Montessori Paradise tem estimativa: 117 reviews verificados no JSON-LD de 11 produtos (piso), divididos por uma taxa de 1% a 3% de review por pedido, em ~8,5 meses de loja, vezes o ticket de US$ 36,97. Mídia = receita x ' + n(CPA_PCT_V, 2) + '% (IRP Baby &amp; Child). As outras ficaram sem número: o proxy de mídia precisa de uma loja medida como âncora, e não há nenhuma. Não usamos as alegações de home ("11.000 reviews", "9.869 reviews", "80K+ customers") como base.', 'a', 'limite')) +
    sec('auditoria', '03', 'Auditoria de contagem de anúncios', '<div class="audit">' + aud2 + '</div>' + note('Cada loja foi achada pelo DOMÍNIO na Biblioteca (não pelo nome) e contada por page_id com ACTIVE e ALL. A toddla.co roda 3 páginas (a marca e 2 perfis de mãe), somadas. Divergência entre ficha e Biblioteca: 0% nas 5.', 'b')) +
    sec('leitura', '04', 'Leitura', evidence({ fonte: 'Meta Ads por page_id, products.json, reviews, prints.', obs: 'As 4 lojas modelo vendem busy board (de US$ 34,97 a US$ 50,60), três delas como campeão, têm catálogo de 43 a 250 itens e vendem bundle.', interp: 'O molde replicável é a loja de busy board de ~US$ 45, vendida pelo sossego sem tela e pelo presente, com bundle no Natal.', dec: 'MODELAR toddla.co (ângulo calmo e UGC), Tibatoes (pré-venda por público e PDF de US$ 9,95), Lovealotter (simplicidade e gancho do interruptor), Montessori Paradise (lista para avó). OBSERVAR Clever Toys Box.', next: 'Ler a ficha da toddla.co antes de escrever os anúncios.' })) +
    footer(false);
  return doc({ title: 'Concorrentes · Montessori', current: 'concorrentes', screen: { code: '03', title: 'Concorrentes' }, body, next: { t: 'Abrir a ficha da loja australiana', b: 'toddla.co', h: 'loja-toddla.html' } });
}

/* ================= 03.x LOJA ================= */
const CAD = {
  toddla: { dia: '~38 por dia (50 anúncios em ~1,3 dia)', sem: '~187 títulos novos por semana', dup: '~1,4x (35 títulos em 50 anúncios)', lon: '~99 dias (busy board)', top: [['(busy board, sem título) → /products/toddla-montessori-busy-board', '99 dias'], ['What To Buy the Grandkids This Christmas, From a Preschool Teacher of 28 Years (2026)', 'outubro de 2026'], ['No batteries. No flashing lights. Just peace. 💛', 'outubro de 2026']], frete: 'AU: A$ 9,95 standard (5 a 10 dias) ou A$ 14,95 express; grátis acima do limite regional', garantia: 'não lida nesta rodada', prazo: 'despacha da China por agente logístico, 5 a 10 dias; BNPL não detectado' },
  tibatoes: { dia: 'rajada: 50 anúncios em ~53 minutos (não extrapolável)', sem: '3 títulos na amostra', dup: '~17x (3 títulos em 50 anúncios)', lon: '~55 dias (busy board, pré-venda)', top: [['The Screen Free Toy Every Child Needs.', '55 dias'], ['The Travel Essential Every Parent Needs', '47 dias'], ['The Screen Free Toy Every Child Needs. (pré-venda TDAH)', '47 dias']], frete: 'grátis acima de US$ 75 (EUA) e A$ 100 (AU); tarifas de importação pagas pela loja', garantia: '30 dias de devolução', prazo: 'preparo em 1 a 2 dias úteis e entrega em 6 a 10 dias úteis; BNPL: Klarna' },
  lovealotter: { dia: '~3,8 por dia (50 anúncios em ~13 dias)', sem: '~5 títulos novos por semana', dup: '~5,6x (9 títulos em 50 anúncios)', lon: '~120 dias (busy board de interruptores)', top: [['⭐⭐⭐⭐⭐50% OFF - Today Only!', '120 dias'], ['Finally, A Toy They\'re Allowed To Touch', '107 dias'], ['Does your toddler touch EVERY switch in the house?', 'setembro de 2026']], frete: 'US$ 6,99, grátis acima de US$ 70', garantia: 'janela não declarada na política lida', prazo: 'preparo em 1 a 2 dias úteis e entrega em 6 a 12 dias úteis, tarifas incluídas; BNPL não detectado' },
  paradise: { dia: '~9,4 por dia (50 anúncios em ~5,3 dias)', sem: '~10 títulos novos por semana', dup: '~6x (8 títulos em 50 anúncios)', lon: '~15 dias (campanha de avó)', top: [['10 Christmas Gifts Grandma Won\'t Regret Buying 🎁', '15 dias'], ['Grandma\'s Favorite Gift 👵', '7 dias'], ['The Screen-Free Favorite Kids Actually Use', 'outubro de 2026']], frete: 'grátis acima de US$ 70', garantia: '45 dias de devolução "no questions asked"', prazo: 'prazo não declarado (página de política de envio retornou 404); BNPL: Klarna' },
  clevertoys: { dia: '~0,2 por dia (19 anúncios em ~90 dias)', sem: 'menos de 1 título novo por semana', dup: '19x (1 título de catálogo)', lon: '~91 dias (anúncio de catálogo)', top: [['Montessori Carrot Set | Montessori Baby Feeding Set | Montessori Busy Bees | ...', '91 dias']], frete: 'grátis acima de US$ 75', garantia: 'devolução "no questions asked" e garantia de 1 ano', prazo: 'origem e prazo não declarados; BNPL não detectado' },
};
const EIXOS = ['Sourcing simples', 'Ticket fecha sem escada complexa', 'Criativo simples de produzir', 'Mecanismo com urgência', 'Investimento de entrada baixo', 'Sem dependência de autoridade de marca'];
const REV = { toddla: 'a home declara 11.000 reviews; nenhuma contagem pública verificável (alegação de marketing)', tibatoes: '~100 reviews verificados em 3 produtos amostrados (piso) via Loox, contra 9.869 declarados na home (alegação)', lovealotter: 'Judge.me instalado, sem contagem pública nas páginas amostradas', paradise: '117 reviews verificados em 11 produtos (piso), contra "80K+ happy customers" na home de uma loja de 9 meses (alegação impossível)', clevertoys: 'Judge.me sem contagem pública; a home declara 415 reviews (alegação)' };
export function loja(l) {
  const myAds = (manifesto.criativos || []).filter(c => (c.linkUrl || '').includes(l.dominio));
  const body = pageHead({ eyebrow: '03 · concorrente · ' + l.modelo.toLowerCase() + ' · nível ' + l.nivel.toLowerCase(), h1: esc(l.nome) + ' ' + pill(l.veredito, VER_CLS[l.veredito]), answer: esc(l.oQueCopiar), meta: ['<a href="https://' + l.dominio + '" target="_blank" rel="noopener">' + l.dominio + ' ↗</a>', 'ativa desde ' + dmy(l.desde) + ' (1º produto do catálogo)', esc(l.plataforma), esc(l.social)] }) +
    '<div class="btns">' + btn('Abrir a loja', 'https://' + l.dominio, 'primary', true) + btn('Biblioteca de anúncios (pelo domínio)', adlib(l.dominio), '', true) + btn('Abrir a página do campeão', l.campeao.url, 'ghost', true) + '</div>' +
    toc([['campeao', 'Produto campeão'], ['midia', 'Mídia paga'], ['trafego', 'Tráfego'], ['faturamento', 'Faturamento'], ['reviews', 'Reviews'], ['paginas', 'Páginas'], ['anatomia', 'Anatomia'], ['catalogo', 'Catálogo e stack'], ['nao-obtido', 'Não obtido'], ['veredito', 'Veredito']]) +
    sec('campeao', '01', 'Produto campeão', '<div class="hero-prod"><img loading="lazy" src="' + l.campeao.img + '" alt="' + attr(l.campeao.titulo) + '"><div><h3>' + esc(l.campeao.titulo) + '</h3><div class="price">' + usd(l.campeao.preco, 2) + (l.campeao.de ? ' <s>' + usd(l.campeao.de, 2) + '</s>' : '') + '</div><p>Desconto anunciado: ' + (l.campeao.de ? pct((1 - l.campeao.preco / l.campeao.de) * 100, 0) : '-') + ' · ticket de referência da loja (mediana do catálogo): ' + usd(l.ticket, 2) + ' ' + nat('obs') + '</p><p>' + esc(l.catalogo) + '</p></div></div>') +
    sec('midia', '02', 'Mídia paga', '<div class="grid g4">' +
      stat({ v: n(l.ativos, 0), l: 'anúncios ativos auditados', k: 'obs', src: 'Meta Ads, page_id' }) +
      stat({ v: n(l.historico, 0), l: 'histórico total', k: 'obs', src: 'Meta Ads, ALL' }) +
      (l.sobrev != null ? stat({ v: pct(l.sobrev), l: dfn('Sobrevivência'), bar: l.sobrev, k: 'calc' }) : stat({ l: dfn('Sobrevivência'), naWhy: 'histórico igual aos ativos na Biblioteca' })) +
      stat({ v: esc(l.google), l: 'Google Ads', k: 'obs', src: 'Transparency Center' }) + '</div>' +
      table(['Ritmo de criativo', 'Valor'], [tr([td('Anúncios por dia'), td(esc(CAD[l.slug].dia))]), tr([td('Criativos únicos por semana'), td(esc(CAD[l.slug].sem))]), tr([td('Duplicação'), td(esc(CAD[l.slug].dup))]), tr([td('Longevidade do anúncio mais antigo ativo'), td(esc(CAD[l.slug].lon))]), tr([td('Leitura (momentum)'), td(esc(l.momento))])]) + '<h3 style="margin-top:16px">Ranking de criativos vencedores</h3>' + table(['#', 'Criativo (título real)', 'Dias no ar', 'Link'], CAD[l.slug].top.map((x, i) => tr([td(i + 1, 'num'), td('"' + esc(x[0]) + '"'), td(esc(x[1])), td('<a href="' + adlib(l.dominio) + '" target="_blank" rel="noopener">Biblioteca de Anúncios ↗</a>')]))) +
      (myAds.length ? '<h3 style="margin-top:16px">Criativos desta loja no top 10 do mercado</h3><div class="ads">' + myAds.map(c => adCard(c)).join('') + '</div>' : '')) +
    sec('trafego', '03', 'Tráfego', note(na('SimilarWeb bloqueou a coleta automática de ' + l.dominio + ' (bloqueio de IP do CloudFront em todas as tentativas); a extensão manual não foi usada por escolha sua') + ' Sinal indireto: ' + ({ toddla: 'Tranco 476 mil, subindo', tibatoes: 'Tranco 1,43 milhão, caindo' }[l.slug] || 'fora do ranking Tranco (tráfego abaixo do limiar dessa lista, o que não quer dizer zero)') + '.', 'a', 'Não obtido') + '<div class="grid g4">' + stat({ l: 'visitas/mês', naWhy: 'SimilarWeb bloqueado' }) + stat({ l: 'pago x orgânico', naWhy: 'SimilarWeb bloqueado' }) + stat({ v: esc(l.social.split(',')[0]), l: 'presença orgânica', d: esc(l.social), k: 'obs', src: 'coletar.mjs' }) + stat({ v: esc(l.google), l: 'outro canal pago', k: 'obs', src: 'Google Ads Transparency' }) + '</div>') +
    sec('faturamento', '04', 'Faturamento e investimento', l.fat ? '<div class="grid g4">' +
      stat({ v: usd(l.fat), l: 'Faturamento mensal (central)', d: 'estimado incerto: proxy de reviews verificados', k: 'inf' }) + stat({ v: usd(l.fatMin), l: 'piso', k: 'inf' }) + stat({ v: usd(l.fatMax), l: 'teto', k: 'inf' }) + stat({ v: usd(l.midiaMes), l: 'mídia/mês estimada', d: n(CPA_PCT_V, 2) + '% da receita (IRP)', k: 'inf' }) + '</div>' +
      note('Método: ' + esc(l.proxy.base) + ', vezes o ticket de US$ 36,97. Selo: <b>estimado incerto</b> (sem SimilarWeb para conferir). Benchmark do setor (IRP ago/2026, Baby &amp; Child): conversão 0,57% (piso), ' + dfn('CPA') + ' 10,92% da receita; ' + dfn('CPM') + ' US$ 10,42 e ' + dfn('CPC') + ' US$ 0,67 (referência pública Meta e-commerce 2026).', 'b')
      : '<div class="grid g4">' + stat({ l: 'Faturamento mensal', naWhy: 'sem visitas medidas e sem reviews verificáveis suficientes' }) + stat({ v: 'não estimado', l: 'selo de confiança', d: 'nem medido nem por proxy: sem base para chutar', k: 'inf' }) + stat({ l: 'mídia/mês estimada', naWhy: 'depende do faturamento, que não foi estimado' }) + stat({ v: n(l.ativos, 0), l: 'anúncios ativos (escala observada)', d: 'o sinal de tamanho que existe', k: 'obs', src: 'Meta Ads' }) + '</div>' +
        note('A Meta não publica gasto de e-commerce fora da UE e o SimilarWeb bloqueou, então a receita desta loja não foi estimada (não usamos proxy de mídia sem uma loja medida como âncora: seria chute). Benchmark do setor (IRP ago/2026, Baby &amp; Child): conversão 0,57% (piso, distorcido por ticket alto), ' + dfn('CPA') + ' 10,92% da receita; ' + dfn('CPM') + ' US$ 10,42 e ' + dfn('CPC') + ' US$ 0,67 (referência pública Meta e-commerce 2026).', 'a')) +
    sec('reviews', '05', 'Reviews', note(esc(REV[l.slug]) + '. Tema de reclamação recorrente ' + na('nenhum app expôs reviews de nota baixa nas páginas amostradas') + '; no nicho todo, a reclamação recorrente é peça que solta e som/pilha (voz do mercado).', 'b')) +
    sec('paginas', '06', 'Páginas da loja', '<div class="shots">' + ['home', 'pdp', 'carrinho'].map(p => '<div class="shot"><div class="cap">' + { home: 'Home', pdp: 'PDP · ' + esc(l.campeao.titulo), carrinho: 'Carrinho com item' }[p] + '</div><div class="frame"><img loading="lazy" src="prints/' + l.slug + '-' + p + '.jpg" alt="' + attr(l.nome + ' ' + p) + '"></div></div>').join('') + '</div>') +
    sec('anatomia', '07', 'Anatomia do vencedor', table(['Elemento', 'Decodificado'], [tr([td('Big idea'), td(esc(l.anatomia.big))]), tr([td('Mecanismo'), td(esc(l.anatomia.mec))]), tr([td('Hook'), td(esc(l.anatomia.hook))]), tr([td('Presell (' + dfn('pré-venda') + ')'), td(esc(l.anatomia.presell))]), tr([td('Objeção principal'), td(esc(l.anatomia.obj))])], { cls: 'kv2' }) +
      table(['Ângulos ativos (títulos reais)'], l.angulos.map(a => tr([td('"' + esc(a) + '"')]))) + note('Momentum da operação: ' + esc(l.momento) + '.', 'b')) +
    sec('catalogo', '08', 'Catálogo e stack', '<dl class="kv"><dt>Plataforma</dt><dd>' + esc(l.plataforma) + '</dd><dt>Apps</dt><dd>' + esc(l.apps) + '</dd><dt>Pixel da Meta</dt><dd>' + na('ID não exposto no HTML lido') + '</dd><dt>Catálogo</dt><dd>' + esc(l.catalogo) + '</dd><dt>Redes</dt><dd>' + esc(l.social) + '</dd><dt>Frete</dt><dd>' + esc(CAD[l.slug].frete) + '</dd><dt>Garantia</dt><dd>' + esc(CAD[l.slug].garantia) + '</dd><dt>Prazo e BNPL</dt><dd>' + esc(CAD[l.slug].prazo) + '</dd><dt>Troca</dt><dd>' + esc(l.retorno) + '</dd><dt>Sinal de fornecedor</dt><dd>' + esc(l.fornecedorSinal) + '</dd></dl>' + note(esc(l.oQueCopiar), 'g', 'o que copiar')) +
    sec('nao-obtido', '09', 'Dados não obtidos', table(['Dado', 'Motivo', 'Método tentado'], l.naoObtido.map(([a, b, c]) => tr([td(esc(a)), td(esc(b)), td(esc(c))])))) +
    sec('veredito', '10', 'Veredito', '<div class="grid g4">' + stat({ v: pill(l.modelo, l.modelo === 'MARCA' ? 'r' : 'g'), l: 'modelo', k: 'inf' }) + stat({ v: pill(l.veredito, VER_CLS[l.veredito]), l: 'veredito', k: 'inf' }) + stat({ v: pill('NÍVEL ' + l.nivel, 'b'), l: 'nível (' + l.score + '/12)', k: 'calc' }) + stat({ v: pill(l.defens, l.defens === 'CONSTRUÍVEL' ? 'g' : 'a'), l: 'defensabilidade', k: 'inf' }) + '</div>' +
      table(['Eixo do scorecard', { t: 'Pontos', num: true }], EIXOS.map((e, i) => tr([td(e), td(l.eixos[i] + '/2', 'num')])).concat([tr([td('<b>Total</b>'), td('<b>' + l.eixos.reduce((a, b) => a + b, 0) + '/12</b>', 'num')])])) +
      evidence({ fonte: 'Meta Ads, products.json, prints, reviews.', obs: esc(l.momento), interp: esc(l.anatomia.big), dec: l.veredito + ' · ' + l.modelo + ' · nível ' + l.nivel, next: esc(l.oQueCopiar), decCls: l.veredito === 'MODELAR' ? '' : 'a' })) +
    footer(false);
  return doc({ title: l.nome + ' · Montessori', current: l.slug, screen: { code: '03', title: l.nome }, body, next: { t: 'Voltar ao índice de concorrentes', b: 'Concorrentes', h: 'concorrentes.html' } });
}

/* ================= 04 ANUNCIOS ================= */
function adCard(c, i = 0) {
  const id = 'proof-' + c.adArchiveId;
  const capa = c.capaLocal || (!c.ehVideo ? c.arquivoLocal : null);
  const media = capa ? '<img loading="lazy" src="criativos/' + path.basename(capa) + '" alt="' + attr(c.pageName) + '">' : '<div class="nomedia"><a href="criativos/' + path.basename(c.arquivoLocal || '') + '" target="_blank">abrir vídeo ↗</a></div>';
  const lib = 'https://www.facebook.com/ads/library/?id=' + c.adArchiveId;
  return '<article class="ad"><div class="media">' + media + '<span class="pill n fmt" style="background:rgba(12,12,10,.85)">' + (c.ehVideo ? 'VÍDEO' : 'IMAGEM') + '</span></div>' +
    '<div class="body"><div class="pg">#' + (c.posicao || i + 1) + ' · ' + esc(c.pageName) + '</div><div class="t">' + esc(c.title && c.title !== '{{product.name}}' ? c.title : '(anúncio dinâmico de catálogo)') + '</div><div class="tx">' + esc((c.bodyText || '').slice(0, 180)) + '</div><div class="days">' + n(c.dias, 0) + ' dias no ar · ' + (c.variacoes || 1) + ' variação(ões)</div></div>' +
    '<div class="foot"><a class="btn sm" href="' + lib + '" target="_blank" rel="noopener">Biblioteca ↗</a>' + (c.ehVideo ? '<a class="btn sm" href="criativos/' + path.basename(c.arquivoLocal || '') + '" target="_blank">Vídeo ↗</a>' : '') + '<button class="btn sm" data-proof="' + id + '">Abrir prova</button></div></article>' +
    '<template id="' + id + '"><span class="eyebrow b">Prova do anúncio</span><h2>' + esc(c.pageName) + '</h2><p style="color:var(--txt)">' + esc(c.bodyText || '') + '</p><dl class="kv"><dt>Fonte</dt><dd><a href="' + lib + '" target="_blank" rel="noopener">Biblioteca de Anúncios da Meta ↗</a></dd><dt>No ar</dt><dd>' + n(c.dias, 0) + ' dias</dd><dt>Destino</dt><dd>' + esc(c.linkUrl || '') + '</dd><dt>Gasto e impressões</dt><dd>' + na('a Meta não publica gasto para e-commerce fora da UE') + '</dd></dl><div class="two"><div class="card proves"><span class="eyebrow g">O que isso prova</span><p style="color:var(--txt)">Que alguém mantém este anúncio no ar há ' + n(c.dias, 0) + ' dias.</p></div><div class="card notproves"><span class="eyebrow a">O que não prova</span><p style="color:var(--txt)">Quanto vende, quanto gasta ou se dá lucro.</p></div></div></template>';
}

export function anuncios() {
  const cr = manifesto.criativos || [];
  const rank = LOJAS.map(l => tr([td('<a href="loja-' + l.slug + '.html">' + esc(l.nome) + '</a>'), td(n(l.ativos, 0), 'num'), td(esc(CAD[l.slug].lon), 'num'), td(esc(l.cad)), td(pill(l.veredito, VER_CLS[l.veredito])), td('<a href="' + adlib(l.dominio) + '" target="_blank" rel="noopener">Biblioteca ↗</a>')]));
  const anat = LOJAS.slice(0, 4).map(l => '<div class="card"><span class="eyebrow ' + VER_CLS[l.veredito] + '">' + esc(l.nome) + '</span><table class="kv2"><tbody>' + [['Big idea', l.anatomia.big], ['Gancho', l.anatomia.hook], ['Ângulo', l.angulos[0]], ['Estrutura', l.anatomia.presell], ['Objeção', l.anatomia.obj], ['Texto na tela / título', l.angulos.slice(0, 2).join(' · ')]].map(([a, b]) => '<tr><td>' + a + '</td><td>' + esc(b) + '</td></tr>').join('') + '</tbody></table></div>').join('');
  const body = pageHead({ eyebrow: '04 · evidências · swipe curado · ' + cr.length + ' criativos baixados de ' + n(MIN, 0) + ' extraídos', h1: 'O que os <em>anúncios</em> que funcionam têm em comum?', answer: 'Os que ficam meses no ar mostram a criança concentrada e falam do adulto ("café ainda quente", "ele nem pediu o iPad"). O argumento "educativo" (motricidade fina) aparece em 21 marcas, mas o que diferencia os vencedores é o sossego e a liberdade de mexer ("finalmente um brinquedo que ele pode tocar").', meta: ['Biblioteca pública, ' + n(MIN, 0) + ' anúncios de ' + MARCAS + ' marcas', n(FILTRADOS, 0) + ' anúncios de ' + MARCAS_F + ' marcas do nicho depois de tirar o ruído', 'criativos salvos em paginas/criativos/'] }) +
    toc([['ranking', 'Ranking de escala'], ['angulos', 'Ângulos'], ['galeria', 'Galeria'], ['anatomia', 'Anatomia dos vencedores'], ['estilo', 'Estilo do criativo'], ['formato', 'Formato e roteiro'], ['lancamento', '5 anúncios de lançamento'], ['limites', 'Fonte e limites']]) +
    sec('ranking', '01', 'Ranking de escala das 5 lojas', table(['Loja', { t: 'Ativos', num: true }, { t: 'Longevidade do campeão', num: true }, 'Ritmo e duplicação', 'Veredito', 'Link'], rank) + note('Longevidade = dias desde o início do anúncio ativo mais antigo. Acima de 60 dias, o anúncio já se pagou. A toddla.co combina as duas coisas que importam: anúncio de 99 dias e muito criativo novo (duplicação de 1,4x).', 'b')) +
    sec('angulos', '02', 'Ângulos que se repetem entre marcas diferentes', '<div class="grid g3">' +
      [['motricidade fina', '"fine motor skills" em 21 marcas, "hand eye coordination" em 15: o argumento padrão, todo mundo usa.'], ['mãos pequenas', '"little hands" em 17 marcas e "little one" em 10: a linguagem é carinhosa, não técnica.'], ['sem tela', '"screen free" em 15 marcas: a culpa da tela é a dor central.'], ['sossego do adulto', 'toddla.co: "Five minutes, coffee still hot", "5pm isn\'t a crisis anymore".'], ['o proibido liberado', 'Lovealotter: "Finally, A Toy They\'re Allowed To Touch"; toddla.co: "The tree they\'re allowed to pull".'], ['presente sem erro', 'Montessori Paradise e Montessori Generation: "Grandma\'s Favorite Gift", "10 Genius Gifts for Grandchildren".']].map(([a, b]) => '<div class="card"><span class="eyebrow g">ângulo</span><h3>' + esc(a) + '</h3><p><small>' + esc(b) + ' · fonte: cruzamento de ' + n(FILTRADOS, 0) + ' anúncios do nicho (swipe.js)</small></p></div>').join('') + '</div>' + btn('Abrir o swipe completo (' + n(FILTRADOS, 0) + ' anúncios)', '../dados/swipe/anuncios.html', 'sm')) +
    sec('galeria', '03', 'Galeria dos ' + cr.length + ' criativos mais escalados do mercado', '<p class="lead">Ordenados por dias no ar (o mais antigo ainda ativo é o vencedor mais provável). Inclui marcas fora do gate de dropship (TinyBusy, Cubby, Montessori Generation, Montessori Toddlers), porque o criativo serve para estudar comunicação.</p><div class="ads">' + cr.map((c, i) => adCard(c, i)).join('') + '</div>' + note('Os 7 vídeos estão salvos completos; a capa é a imagem de prévia da própria Biblioteca, porque o ffmpeg não está instalado nesta máquina (sem transcrição de áudio). A decodificação abaixo usa a copy real de cada anúncio.', 'a', 'limite')) +
    sec('anatomia', '04', 'Anatomia dos vencedores', '<p class="lead">Os 4 concorrentes mais escalados entre as lojas analisadas, decodificados a partir da copy real dos anúncios.</p><div class="grid g2">' + anat + '</div>') +
    sec('estilo', '05', 'Estilo do criativo', '<div class="grid g4">' + stat({ v: '66%', l: 'vídeo', d: '384 de ' + n(FILTRADOS, 0) + ' anúncios do nicho', k: 'obs' }) + stat({ v: '18%', l: 'imagem', d: '107 anúncios', k: 'obs' }) + stat({ v: '14%', l: 'dinâmico (DCO)', d: '82 anúncios', k: 'obs' }) + stat({ v: '0', l: 'marcados como gerados por IA', k: 'obs' }) + '</div>' +
      '<div class="card" style="margin-top:12px"><span class="eyebrow b">leitura dos 10 da galeria</span><p>Demonstração de produto com criança real brincando (toddla.co, Lovealotter, Montessori Toddlers) domina; ' + dfn('UGC') + ' em 1ª pessoa de mãe aparece na toddla.co (2 perfis de mãe dedicados); imagem estática de produto com oferta ("50% OFF - Today Only") na Lovealotter; lista de presentes em texto (Montessori Generation, Montessori Paradise). Nenhum usa influenciador famoso: é filmagem caseira de criança, barata de produzir.</p></div>') +
    sec('formato', '06', 'Formato e roteiro', table(['Formato', 'Roteiro', 'Uso no seu plano'], [tr([td('Vídeo de demonstração (15 a 30s)'), td('criança mexendo num interruptor da casa → mãe tira a mão dela → criança no board, concentrada → café/jantar ao fundo → oferta'), td('anúncio 1 (o proibido liberado)')]), tr([td('UGC em 1ª pessoa (20 a 40s)'), td('"5pm used to be a crisis..." → o que mudou → board → 20 minutos de sossego'), td('anúncio 2 (sossego)')]), tr([td('Vídeo de prova de segurança (10s)'), td('mão adulta puxa forte cada interruptor → nada sai → tampa da pilha com parafuso'), td('anúncio 3 (a brecha: ninguém mostra)')]), tr([td('Lista para avó (imagem ou carrossel)'), td('"The gift grandkids actually play with" → kit → oferta de Natal'), td('anúncio 4 (outubro a dezembro)')]), tr([td('Catálogo dinâmico'), td('produto + preço'), td('só depois de 30 vendas (precisa de pixel com dados)')])])) +
    sec('lancamento', '07', '5 anúncios de lançamento', table(['#', 'Gancho (texto na tela)', 'Ângulo', 'Referência na Biblioteca'], [
      tr([td('1', 'num'), td('"The switches they\'re actually allowed to touch."'), td('o proibido liberado (Lovealotter)'), td('<a href="' + adlib('lovealotter.com') + '" target="_blank" rel="noopener">Lovealotter ↗</a>')]),
      tr([td('2', 'num'), td('"Twenty minutes. Coffee still hot."'), td('sossego do adulto, UGC (toddla.co)'), td('<a href="' + adlib('toddla.co') + '" target="_blank" rel="noopener">toddla.co ↗</a>')]),
      tr([td('3', 'num'), td('"We pull every switch before it ships. Nothing comes off."'), td('prova de segurança (a brecha do nicho)'), td('sem referência direta: ninguém roda isso')]),
      tr([td('4', 'num'), td('"No screen. No noise. Just busy hands."'), td('sem tela (15 marcas)'), td('<a href="' + adlib('tibatoes.com') + '" target="_blank" rel="noopener">Tibatoes ↗</a>')]),
      tr([td('5', 'num'), td('"The gift the grandkids actually play with."'), td('presente sem erro (Montessori Paradise)'), td('<a href="' + adlib('montessoriparadise.com') + '" target="_blank" rel="noopener">Montessori Paradise ↗</a>')]),
    ]) + note('Os roteiros completos ficam na pasta 07-anuncios da marca. Não use promessa médica (TDAH, autismo, "desenvolvimento cerebral"): a Tibatoes usa, e é risco de reprovação e de reclamação.', 'a')) +
    sec('limites', '08', 'Fonte e limites', note('Gasto e impressões não existem na fonte para anúncio comercial fora da UE. Contagem de anúncio prova que alguém paga para manter o anúncio, não que ele dá lucro. A amostra da Biblioteca vem ordenada por recência; a longevidade foi lida pela data de início. ' + n(MIN - FILTRADOS, 0) + ' anúncios de ruído (romance, drama, escola Montessori, pet, presente de escalada) foram retirados antes de montar a galeria e o swipe.', 'a') + legendNat()) +
    footer(false);
  return doc({ title: 'Criativos e prova · Montessori', current: 'anuncios', screen: { code: '04', title: 'Criativos e prova' }, body, next: { t: 'Ver como transformar isso em estratégia', b: 'Estratégia', h: 'estrategia.html' } });
}
